import {makeResponseWithLoading} from "./util/index.mjs";
async function Module(moduleArg={}){var moduleRtn;var g=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,k=ba&&self.name?.startsWith("em-pthread"),ca=import.meta.url,da="",ea,fa;if(aa||ba){try{da=(new URL(".",ca)).href}catch{}ba&&(fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}
var ha=console.log.bind(console),p=console.error.bind(console),ia,ja=!1,ka;function q(){la.buffer!=w.buffer&&ma()}var na,oa,pa;
if(k){var ra=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.Vg;if("load"===d){let e=[];self.onmessage=f=>e.push(f);pa=()=>{postMessage({Vg:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.Ti)if(!g[f]||g[f].proxy)g[f]=(...h)=>{postMessage({Vg:"callHandler",Si:f,Ji:h})},"print"==f&&(ha=g[f]),"printErr"==f&&(p=g[f]);la=c.jj;ma();ia=c.kj;sa();ta()}else if("run"===d){ua(c.Sg);va(c.Sg,0,0,1,0,0);wa(c);xa();ya(c.Sg);ra||(za(),ra=!0);try{Aa(c.hj,c.zh)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?ra&&Ba():d&&(p(`worker: received unknown command ${d}`),p(c)))}catch(e){throw Ca(),e;}}self.onmessage=a}var w,x,A,Da,B,C,Ea,F,Fa,Ga,Ha=!1,Ia=!1;function ma(){var a=la.buffer;w=new Int8Array(a);A=new Int16Array(a);x=new Uint8Array(a);Da=new Uint16Array(a);B=new Int32Array(a);C=new Uint32Array(a);Ea=new Float32Array(a);F=new Float64Array(a);Fa=new BigInt64Array(a);Ga=new BigUint64Array(a)}function Ja(){Ha=!0;k?pa():Ka.Bd()}
function La(a){a="Aborted("+a+")";p(a);ja=!0;a+=". Build with -sASSERTIONS for more info.";Ha&&Ma();a=new WebAssembly.RuntimeError(a);oa?.(a);throw a;}var Na;async function Oa(a){try{var b=await ea(a);return new Uint8Array(b)}catch{}if(fa)a=fa(a);else throw"both async and sync fetching of the wasm failed";return a}async function Pa(a,b){try{var c=await Oa(a);return await WebAssembly.instantiate(c,b)}catch(d){p(`failed to asynchronously prepare wasm: ${d}`),La(d)}}
async function Qa(a){var b=Na;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(makeResponseWithLoading(c),a)}catch(d){p(`wasm streaming compile failed: ${d}`),p("falling back to ArrayBuffer instantiation")}return Pa(b,a)}
function Ra(){Sa={Bb:Ta,hb:Ua,kc:Va,Dc:Wa,Pc:Xa,o:Ya,gb:Za,ic:$a,gc:ab,s:bb,g:cb,fb:db,i:eb,T:fb,y:gb,hc:hb,Ja:ib,E:jb,l:kb,jc:lb,Fc:mb,Kc:nb,Ac:ob,Ec:pb,lc:qb,jb:rb,Jc:ya,Nc:sb,f:tb,c:ub,Db:vb,j:wb,h:xb,e:yb,ga:zb,ib:Ab,k:Bb,d:Cb,mc:Db,Gc:Eb,Hc:Fb,Ic:Gb,nc:Hb,Rc:Ib,uc:Jb,sc:Kb,tc:Lb,qc:Mb,oc:Nb,vc:Ob,rc:Pb,pc:Qb,xc:Rb,Ad:Sb,Tb,Nb:Ub,Ob:Vb,Ub:Wb,Vb:Xb,Rb:Yb,Sb:Zb,Pb:$b,Xa:ac,Qb:bc,na:cc,Ya:dc,Oc:ec,cb:fc,yd:gc,r:hc,Cb:ic,Za:jc,kb:kc,D:lc,Ka:mc,qa:nc,$a:oc,Sc:pc,zb:qc,eb:rc,db:sc,Ha:tc,Bc:uc,b:vc,
Xb:wc,Wb:xc,Yb:yc,Ga:zc,ia:Ac,wc:Bc,Ab:Cc,fc:Dc,zc:Ec,Ia:Fc,ab:Gc,mb:Hc,lb:Ic,ec:Jc,_a:Kc,tb:Lc,rb:Mc,sb:Nc,pb:Oc,ob:Pc,qb:Qc,nb:Rc,jd:Sc,id:Tc,Tc:Uc,Cc:Vc,Vc:Wc,Wc:Xc,ub:Yc,Uc:Zc,bc:$c,dc:ad,Lc:bd,Mc:cd,Pa:dd,vd:ed,cc:fd,_:gd,$c:hd,q:jd,A:kd,R:ld,w:md,m:nd,Ta:od,$:pd,gd:qd,I:rd,Qa:sd,Jb:td,za:ud,ja:vd,Hb:wd,Va:xd,cd:yd,ad:zd,ed:Ad,Fa:Bd,z:Cd,ma:Dd,vb:Ed,da:Fd,Oa:Gd,K:Hd,H:Id,W:Jd,fa:Kd,Xc:Ld,x:Md,J:Nd,Kb:Od,Ra:Pd,p:Qd,G:Rd,Q:Sd,Ca:Td,Ea:Ud,O:Vd,la:Wd,ca:Xd,X:Yd,N:Zd,hd:$d,Yc:ae,Ma:be,Da:ce,Y:de,
V:ee,Zc:fe,wb:ie,bd:je,xb:ke,n:le,C:me,ea:ne,Lb:oe,La:pe,Mb:qe,pa:re,U:se,_c:te,ka:ue,Wa:ve,Aa:we,Ua:xe,Ba:ye,yb:ze,Sa:Ae,dd:Be,S:Ce,u:De,ha:Ee,B:Fe,L:Ge,Na:He,oa:Ie,fd:Je,aa:Ke,v:Le,t:Me,F:Ne,P:Oe,ac:Pe,$b:Qe,wd:Re,a:la,md:Se,zd:Te,Qc:Ue,yc:Ve,Zb:We,Ib:Xe,_b:Ye,bb:Ze,ld:$e,pd:af,sd:bf,od:cf,nd:df,va:ef,qd:ff,sa:gf,ba:hf,M:jf,Gb:kf,xa:lf,ya:mf,td:nf,kd:of,ra:pf,Fb:qf,ta:rf,ua:sf,wa:tf,ud:uf,Eb:vf,Z:wf,rd:xf,xd:yf};return{a:Sa}}
async function sa(){function a(c,d){Ka=c.exports;zf.push(Ka.lg);c=Ka;Af=c.Cd;za=c.Dd;Bf=c.Ed;Cf=c.Fd;g.__ZN6google10LogMessage9LogStreamC2EPcix=c.Gd;g.__ZN6google10LogMessage9LogStreamC1EPcix=c.Hd;g.__ZN4shen10InitializeENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES6_NS_23initialization_settingsE=c.Id;g.__ZN4shen13IsInitializedEv=c.Jd;g.__ZN4shen12DeinitializeEv=c.Kd;g.__ZN4shen15FinalizeTracingEv=c.Ld;g.__ZN4shen18GetSDKConfigStringEv=c.Md;g.__ZN4shen14ApplySDKConfigENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE=
c.Nd;g.__ZN4shen16SetOperatingModeENS_13OperatingModeE=c.Od;g.__ZN4shen16GetOperatingModeEv=c.Pd;g.__ZN4shen9SetScreenENS_6ScreenE=c.Qd;g.__ZN4shen9GetScreenEv=c.Rd;g.__ZN4shen16SetPrecisionModeENS_13PrecisionModeE=c.Sd;g.__ZN4shen16GetPrecisionModeEv=c.Td;g.__ZN4shen20SetMeasurementPresetENS_17MeasurementPresetE=c.Ud;g.__ZN4shen20GetMeasurementPresetEv=c.Vd;g.__ZN4shen22SetBpCalibrationOffsetEdd=c.Wd;g.__ZN4shen26GetCustomMeasurementConfigEv=c.Xd;g.__ZN4shen26SetCustomMeasurementConfigENS_25custom_measurement_configE=
c.Yd;g.__ZN4shen19SetCustomColorThemeENS_18custom_color_themeE=c.Zd;g.__ZN4shen19GetCustomColorThemeEv=c._d;g.__ZN4shen13SetCameraModeENS_10CameraModeE=c.$d;g.__ZN4shen13GetCameraModeEv=c.ae;g.__ZN4shen22SelectCameraByDeviceIdENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_8optionalIbEE=c.be;g.__ZN4shen14SetMediaStreamENSt3__23anyENS0_8optionalIbEE=c.ce;g.__ZN4shen20SetShowUserInterfaceEb=c.de;g.__ZN4shen20GetShowUserInterfaceEv=c.ee;g.__ZN4shen29SetShowFacePositioningOverlayEb=
c.fe;g.__ZN4shen29GetShowFacePositioningOverlayEv=c.ge;g.__ZN4shen21SetShowVisualWarningsEb=c.he;g.__ZN4shen21GetShowVisualWarningsEv=c.ie;g.__ZN4shen19SetEnableCameraSwapEb=c.je;g.__ZN4shen19GetEnableCameraSwapEv=c.ke;g.__ZN4shen15SetShowFaceMaskEb=c.le;g.__ZN4shen15GetShowFaceMaskEv=c.me;g.__ZN4shen16SetShowBloodFlowEb=c.ne;g.__ZN4shen16GetShowBloodFlowEv=c.oe;g.__ZN4shen26SetEnableStartAfterSuccessEb=c.pe;g.__ZN4shen26GetEnableStartAfterSuccessEv=c.qe;g.__ZN4shen17SetHideShenaiLogoEb=c.re;g.__ZN4shen17GetHideShenaiLogoEv=
c.se;g.__ZN4shen33SetShowOutOfRangeResultIndicatorsEb=c.te;g.__ZN4shen33GetShowOutOfRangeResultIndicatorsEv=c.ue;g.__ZN4shen24SetShowTrialMetricLabelsEb=c.ve;g.__ZN4shen24GetShowTrialMetricLabelsEv=c.we;g.__ZN4shen17SetShowSignalTileEb=c.xe;g.__ZN4shen17GetShowSignalTileEv=c.ye;g.__ZN4shen29SetShowSignalQualityIndicatorEb=c.ze;g.__ZN4shen29GetShowSignalQualityIndicatorEv=c.Ae;g.__ZN4shen22SetShowStartStopButtonEb=c.Be;g.__ZN4shen22GetShowStartStopButtonEv=c.Ce;g.__ZN4shen17SetShowInfoButtonEb=c.De;
g.__ZN4shen17GetShowInfoButtonEv=c.Ee;g.__ZN4shen17GetShowDisclaimerEv=c.Fe;g.__ZN4shen30SetEnableMeasurementsDashboardEb=c.Ge;g.__ZN4shen30GetEnableMeasurementsDashboardEv=c.He;g.__ZN4shen16SetUiFlowScreensENSt3__26vectorINS_6ScreenENS0_9allocatorIS2_EEEE=c.Ie;g.__ZN4shen16GetUiFlowScreensEv=c.Je;g.__ZN4shen12GetFaceStateEv=c.Ke;g.__ZN4shen21GetNormalizedFaceBboxEv=c.Le;g.__ZN4shen19GetMeasurementStateEv=c.Me;g.__ZN4shen32GetMeasurementProgressPercentageEv=c.Ne;g.__ZN4shen15GetHeartRate10sEv=c.Oe;
g.__ZN4shen14GetHeartRate4sEv=c.Pe;g.__ZN4shen20GetRealtimeHeartRateEv=c.Qe;g.__ZN4shen18GetRealtimeHrvSdnnEv=c.Re;g.__ZN4shen24GetRealtimeCardiacStressEv=c.Se;g.__ZN4shen18GetRealtimeMetricsEf=c.Te;g.__ZN4shen21GetMeasurementResultsEv=c.Ue;g.__ZN4shen28GetMeasurementResultsHistoryEv=c.Ve;g.__ZN4shen21GetHealthRisksFactorsEv=c.We;g.__ZN4shen23clearHealthRisksFactorsEv=c.Xe;g.__ZN4shen14GetHealthRisksEv=c.Ye;g.__ZN4shen18ComputeHealthRisksERKN2mx12health_risks12RisksFactorsE=c.Ze;g.__ZN4shen15GetMaximalRisksERKN2mx12health_risks12RisksFactorsE=
c._e;g.__ZN4shen15GetMinimalRisksERKN2mx12health_risks12RisksFactorsE=c.$e;g.__ZN4shen17GetReferenceRisksERKN2mx12health_risks12RisksFactorsE=c.af;g.__ZN4shen21GetRealtimeHeartbeatsENSt3__28optionalIfEE=c.bf;g.__ZN4shen11GetFacePoseEv=c.cf;g.__ZN4shen19SetRecordingEnabledEb=c.df;g.__ZN4shen19GetRecordingEnabledEv=c.ef;g.__ZN4shen24GetTotalBadSignalSecondsEv=c.ff;g.__ZN4shen29GetCurrentSignalQualityMetricEv=c.gf;g.__ZN4shen22GetSignalQualityMapPngEv=c.hf;g.__ZN4shen17GetFaceTexturePngEv=c.jf;g.__ZN4shen25GetMetaPredictionImagePngEv=
c.kf;g.__ZN4shen16GetFullPPGSignalEv=c.lf;g.__ZN4shen10GetTraceIDEv=c.mf;g.__ZN4shen16GetMeasurementIDEv=c.nf;g.__ZN4shen11SetLanguageENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE=c.of;g.__ZN4shen19GetSelectedLanguageEv=c.pf;g.__ZN4shen14GetPricingPlanEv=c.qf;g.__ZN4shen28GetEnableFullFrameProcessingEv=c.rf;g.__ZN4shen28SetEnableFullFrameProcessingEb=c.sf;g.__ZN4shen20GetCameraAspectRatioEv=c.tf;g.__ZN4shen20SetCameraAspectRatioEd=c.uf;g.__ZN4shen22GetEnableSummaryScreenEv=c.vf;
g.__ZN4shen22SetEnableSummaryScreenEb=c.wf;g.__ZN4shen26GetShowResultsFinishButtonEv=c.xf;g.__ZN4shen26SetShowResultsFinishButtonEb=c.yf;g.__ZN4shen20GetEnableHealthRisksEv=c.zf;g.__ZN4shen20SetEnableHealthRisksEb=c.Af;g.__ZN4shen32GetShowHealthIndicesFinishButtonEv=c.Bf;g.__ZN4shen32SetShowHealthIndicesFinishButtonEb=c.Cf;g.__ZN4shen17GetOnboardingModeEv=c.Df;g.__ZN4shen17SetOnboardingModeENS_14OnboardingModeE=c.Ef;g.__ZN4shen19GetCalibrationStateEv=c.Ff;g.__ZN4shen10GetVersionEv=c.Gf;g.__ZN4shen18GetCalibrationDataEv=
c.Hf;g.__ZN4shen23GetSbpCalibrationOffsetEv=c.If;g.__ZN4shen23GetDbpCalibrationOffsetEv=c.Jf;g.__ZN4shen32SendMeasurementResultsPdfToEmailENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_8functionIFvbEEE=c.Kf;g.__ZN4shen34OpenMeasurementResultsPdfInBrowserEv=c.Lf;g.__ZN4shen27GetMeasurementResultsPdfUrlENSt3__28functionIFvNS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEEEE=c.Mf;g.__ZN4shen31RequestMeasurementResultsPdfUrlEv=c.Nf;g.__ZN4shen27GetMeasurementResultsPdfUrlEv=
c.Of;g.__ZN4shen29GetMeasurementResultsPdfBytesENSt3__28functionIFvNS0_6vectorIhNS0_9allocatorIhEEEEEEE=c.Pf;g.__ZN4shen33RequestMeasurementResultsPdfBytesEv=c.Qf;g.__ZN4shen29GetMeasurementResultsPdfBytesEv=c.Rf;g.__ZN4shen26GetResultAsFhirObservationEv=c.Sf;g.__ZN4shen25SendResultFhirObservationENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_8functionIFvS6_EEE=c.Tf;g._handlePagehide=c.Uf;Df=g._main=c.Vf;H=c.Wf;Ef=c.Xf;g._onVideoDevicesEnumerated=c.Yf;g._onVideoDevicesEnumerationError=
c.Zf;g._onCameraInitialized=c._f;g._onCameraInitializationError=c.$f;g._ingestCameraFrame=c.ag;I=c.bg;g._onBleDeviceReady=c.cg;g._onBleControlNotification=c.dg;g._onBleDataNotification=c.eg;g._bm_onReady=c.fg;g._bm_onRx=c.gg;Ff=c.hg;g.__ZN6google15NullStreamFatalD2Ev=c.ig;g.__ZN6google15NullStreamFatalD1Ev=c.jg;g.__ZN6google15NullStreamFatalD0Ev=c.kg;Gf=c.ng;va=c.og;Ca=c.pg;Hf=c.qg;If=c.rg;Jf=c.sg;Kf=c.tg;Lf=c.ug;Ma=c.vg;Mf=c.wg;Nf=c.xg;Of=c.yg;Pf=c.zg;Qf=c.mg;ia=d;return Ka}var b=Ra();if(k)return b=
new WebAssembly.Instance(ia,Ra()),a(b,ia);Na??=g.locateFile?g.locateFile?g.locateFile("shenai_sdk.wasm",da):da+"shenai_sdk.wasm":(new URL("shenai_sdk.wasm",import.meta.url)).href;return function(c){return a(c.instance,c.module)}(await Qa(b))}class Rf{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Sf=a=>{a.terminate();a.onmessage=()=>{}},Tf=[],Yf=a=>{if(0==Uf.length){var b=new Worker(new URL("shenai_sdk.mjs",import.meta.url),{type:"module",name:"em-pthread"});Uf.push(b);Vf()}b=Uf.pop();if(!b)return 6;Wf.push(b);Xf[a.Sg]=b;b.Sg=a.Sg;var c={Vg:"run",hj:a.gj,zh:a.zh,Sg:a.Sg};c.dh=a.dh;c.Ph=a.Ph;b.postMessage(c,a.zi);return 0},J=0,L=(a,b,...c)=>{for(var d=2*c.length,e=Pf(),f=Of(8*d),h=f>>3,l=0;l<c.length;l++){var m=c[l];"bigint"==typeof m?((q(),Fa)[h+2*l]=1n,(q(),Fa)[h+2*l+1]=m):
((q(),Fa)[h+2*l]=0n,(q(),F)[h+2*l+1]=m)}a=Hf(a,0,d,f,b);Nf(e);return a};function Ue(a){if(k)return L(0,1,a);ka=a;0<J||(Zf(),ja=!0);throw new Rf(a);}function $f(a){if(k)return L(1,0,a);dd(a)}var dd=a=>{ka=a;if(k)throw $f(a),"unwind";if(!(0<J||k)){Gf();for(var b=ag;0<b.length;)b.shift()(g);Zf();Ia=!0}Ue(a)},Uf=[],Wf=[],zf=[],Xf={},Zf=()=>{for(var a of Wf)Sf(a);for(a of Uf)Sf(a);Uf=[];Wf=[];Xf={}},bg=a=>{var b=a.Sg;delete Xf[b];Uf.push(a);Wf.splice(Wf.indexOf(a),1);a.Sg=0;If(b)};
function wa(a){"undefined"!=typeof cg&&(Object.assign(dg,a.Ph),!g.canvas&&a.dh&&dg[a.dh]&&(g.canvas=dg[a.dh].Rg,g.canvas.id=a.dh))}function xa(){zf.forEach(a=>a())}
var Vf=()=>{var a=Uf[0];new Promise(b=>{a.onmessage=f=>{var h=f.data;f=h.Vg;if(h.Fh&&h.Fh!=Ef()){var l=Xf[h.Fh];l?l.postMessage(h,h.zi):p(`Internal error! Worker sent a message "${f}" to target pthread ${h.Fh}, but that thread no longer exists!`)}else if("checkMailbox"===f)Ba();else if("spawnThread"===f)Yf(h);else if("cleanupThread"===f)eg(()=>{bg(Xf[h.ij])});else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===h.target)a.postMessage(h);else if("callHandler"===f)g[h.Si](...h.Ji);else f&&
p(`worker sent an unknown command ${f}`)};a.onerror=f=>{p(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["print"],e;for(e of d)g.propertyIsEnumerable(e)&&c.push(e);a.postMessage({Vg:"load",Ti:c,jj:la,kj:ia})})},fg;function ua(a){var b=(q(),C)[a+52>>2];a=(q(),C)[a+56>>2];Mf(b,b-a);Nf(b)}
var gg=[],M=a=>{var b=gg[a];b||(gg[a]=b=Qf.get(a));return b},Aa=(a,b)=>{J=0;a=M(a)(b);0<J?ka=a:Jf(a)},la,hg=globalThis.TextDecoder&&new TextDecoder,ig=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},jg=(a,b=0,c,d)=>{c=ig(a,b,c,d);if(16<c-b&&a.buffer&&hg)return hg.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<
12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},P=(a,b,c)=>a?jg((q(),x),a,b,c):"",Ua=(a,b,c,d)=>La(`Assertion failed: ${P(a)}, at: `+[b?P(b):"unknown filename",c,d?P(d):"unknown function"]),Va=(a,b)=>M(a)(b);function kg(a,b,c,d){return k?L(2,1,a,b,c,d):Wa(a,b,c,d)}
var Wa=(a,b,c,d)=>{if(!globalThis.SharedArrayBuffer)return 6;var e=[],f=0,h=b?(q(),C)[b+40>>2]:0;h=(h=4294967295==h?"#canvas":P(h).trim())?h.split(","):[];var l={},m=g.canvas?.id||"";for(n of h){var n=n.trim();try{if("#canvas"==n){if(!g.canvas){p(`pthread_create: could not find canvas with ID "${n}" to transfer to thread!`);f=28;break}n=g.canvas.id}if(dg[n]){var r=dg[n];dg[n]=null;g.canvas instanceof OffscreenCanvas&&n===g.canvas.id&&(g.canvas=null)}else if(!k){var u=g.canvas&&g.canvas.id===n?g.canvas:
document.querySelector(n);if(!u){p(`pthread_create: could not find canvas with ID "${n}" to transfer to thread!`);f=28;break}if(u.kh){p(`pthread_create: cannot transfer canvas with ID "${n}" to thread, since the current thread does not have control over it!`);f=63;break}if(u.transferControlToOffscreen)u.Hg||(u.Hg=H(12),(q(),B)[u.Hg>>2]=u.width,(q(),B)[u.Hg+4>>2]=u.height,(q(),C)[u.Hg+8>>2]=0),r={Rg:u.transferControlToOffscreen(),Hg:u.Hg,id:u.id},u.kh=!0;else return p(`pthread_create: cannot transfer control of canvas "${n}" to pthread, because current browser does not support OffscreenCanvas!`),
p("pthread_create: Build with -sOFFSCREEN_FRAMEBUFFER to enable fallback proxying of GL commands from pthread to main thread."),52}r&&(e.push(r.Rg),l[r.id]=r)}catch(t){return p(`pthread_create: failed to transfer control of canvas "${n}" to OffscreenCanvas! Error: ${t}`),28}}if(k&&(0===e.length||f))return kg(a,b,c,d);if(f)return f;for(u of Object.values(l))(q(),C)[u.Hg+8>>2]=a;a={gj:c,Sg:a,zh:d,dh:m,Ph:l,zi:e};return k?(a.Vg="spawnThread",postMessage(a,e),0):Yf(a)},Xa=()=>La(""),lg={},mg=a=>{for(;a.length;){var b=
a.pop();a.pop()(b)}};function ng(a){return this.Dg((q(),C)[a>>2])}
var og={},pg={},qg={},rg=class extends Error{constructor(a){super(a);this.name="InternalError"}},tg=(a,b,c)=>{function d(l){l=c(l);if(l.length!==a.length)throw new rg("Mismatched type converter count");for(var m=0;m<a.length;++m)sg(a[m],l[m])}a.forEach(l=>qg[l]=b);var e=Array(b.length),f=[],h=0;for(let [l,m]of b.entries())pg.hasOwnProperty(m)?e[l]=pg[m]:(f.push(m),og.hasOwnProperty(m)||(og[m]=[]),og[m].push(()=>{e[l]=pg[m];++h;h===f.length&&d(e)}));0===f.length&&d(e)},Ya=a=>{var b=lg[a];delete lg[a];
var c=b.Yi,d=b.Zi,e=b.ii,f=e.map(h=>h.Ri).concat(e.map(h=>h.ej));tg([a],f,h=>{var l={},m,n;for([m,n]of e.entries()){const r=h[m],u=n.Pi,t=n.Qi,v=h[m+e.length],z=n.dj,O=n.fj;l[n.Ni]={read:D=>r.Dg(u(t,D)),write:(D,G)=>{var E=[];z(O,D,v.Lg(E,G));mg(E)},optional:r.optional}}return[{name:b.name,Dg:r=>{var u={},t;for(t in l)u[t]=l[t].read(r);d(r);return u},Lg:(r,u)=>{for(var t in l)if(!(t in u||l[t].optional))throw new TypeError(`Missing field: "${t}"`);var v=c();for(t in l)l[t].write(v,u[t]);null!==r&&
r.push(d,v);return v},Tg:ng,Og:d}]})},Q=a=>{for(var b="";;){var c=(q(),x)[a++];if(!c)return b;b+=String.fromCharCode(c)}},ug=class extends Error{constructor(a){super(a);this.name="BindingError"}},vg=a=>{throw new ug(a);};
function wg(a,b,c={}){var d=b.name;if(!a)throw new ug(`type "${d}" must have a positive integer typeid pointer`);if(pg.hasOwnProperty(a)){if(c.Ui)return;throw new ug(`Cannot register type '${d}' twice`);}pg[a]=b;delete qg[a];og.hasOwnProperty(a)&&(b=og[a],delete og[a],b.forEach(e=>e()))}function sg(a,b,c={}){return wg(a,b,c)}
var xg=(a,b,c)=>{switch(b){case 1:return c?d=>(q(),w)[d]:d=>(q(),x)[d];case 2:return c?d=>(q(),A)[d>>1]:d=>(q(),Da)[d>>1];case 4:return c?d=>(q(),B)[d>>2]:d=>(q(),C)[d>>2];case 8:return c?d=>(q(),Fa)[d>>3]:d=>(q(),Ga)[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Za=(a,b,c,d,e)=>{b=Q(b);d=0n===d;let f=h=>h;if(d){const h=8*c;f=l=>BigInt.asUintN(h,l);e=f(e)}sg(a,{name:b,Dg:f,Lg:(h,l)=>{"number"==typeof l&&(l=BigInt(l));return l},Tg:xg(b,c,!d),Og:null})},$a=(a,b,c,d)=>{b=
Q(b);sg(a,{name:b,Dg:function(e){return!!e},Lg:function(e,f){return f?c:d},Tg:function(e){return this.Dg((q(),x)[e])},Og:null})},yg=[],zg=[0,1,,1,null,1,!0,1,!1,1],ub=a=>{9<a&&0===--zg[a+1]&&(zg[a]=void 0,yg.push(a))},Ag=a=>{if(!a)throw new ug(`Cannot use deleted val. handle = ${a}`);return zg[a]},Bg=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=yg.pop()||zg.length;zg[b]=a;zg[b+1]=1;return b}},Cg={name:"emscripten::val",Dg:a=>{var b=Ag(a);
ub(a);return b},Lg:(a,b)=>Bg(b),Tg:ng,Og:null},ab=a=>sg(a,Cg),Dg=(a,b)=>{if(void 0===g[a].Qg){var c=g[a];g[a]=function(...d){if(!g[a].Qg.hasOwnProperty(d.length))throw new ug(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${g[a].Qg})!`);return g[a].Qg[d.length].apply(this,d)};g[a].Qg=[];g[a].Qg[c.bi]=c}},Eg=(a,b,c)=>{if(g.hasOwnProperty(a)){if(void 0===c||void 0!==g[a].Qg&&void 0!==g[a].Qg[c])throw new ug(`Cannot register public name '${a}' twice`);Dg(a,
a);if(g[a].Qg.hasOwnProperty(c))throw new ug(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);g[a].Qg[c]=b}else g[a]=b,g[a].bi=c},Fg=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.Dg((q(),w)[d])}:function(d){return this.Dg((q(),x)[d])};case 2:return c?function(d){return this.Dg((q(),A)[d>>1])}:function(d){return this.Dg((q(),Da)[d>>1])};case 4:return c?function(d){return this.Dg((q(),B)[d>>2])}:function(d){return this.Dg((q(),C)[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}},bb=(a,b,c,d)=>{function e(){}b=Q(b);e.values={};sg(a,{name:b,constructor:e,Dg:function(f){return this.constructor.values[f]},Lg:(f,h)=>h.value,Tg:Fg(b,c,d),Og:null});Eg(b,e)},Gg=(a,b)=>Object.defineProperty(b,"name",{value:a}),Hg=a=>{a=Af(a);var b=Q(a);I(a);return b},Ig=(a,b)=>{var c=pg[a];if(void 0===c)throw a=`${b} has unknown type ${Hg(a)}`,new ug(a);return c},cb=(a,b,c)=>{var d=Ig(a,"enum");b=Q(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Gg(`${d.name}_${b}`,
function(){})}});a.values[c]=d;a[b]=d},Jg=(a,b)=>{switch(b){case 4:return function(c){return this.Dg((q(),Ea)[c>>2])};case 8:return function(c){return this.Dg((q(),F)[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},db=(a,b,c)=>{b=Q(b);sg(a,{name:b,Dg:d=>d,Lg:(d,e)=>e,Tg:Jg(b,c),Og:null})};function Kg(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Og)return!0;return!1}
var Lg=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push((q(),C)[b+4*d>>2]);return c},Ng=(a,b)=>{a=Q(a);var c=M(b);if("function"!=typeof c)throw new ug(`unknown function pointer with signature ${a}: ${b}`);return c};class Og extends Error{}
var Pg=(a,b)=>{function c(f){e[f]||pg[f]||(qg[f]?qg[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Og(`${a}: `+d.map(Hg).join([", "]));},Qg=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},eb=(a,b,c,d,e,f,h)=>{var l=Lg(b,c);a=Q(a);a=Qg(a);e=Ng(d,e);Eg(a,function(){Pg(`Cannot call ${a} due to unbound types`,l)},b-1);tg([],l,m=>{var n=a;var r=a;m=[m[0],null].concat(m.slice(1));var u=e,t=m.length;if(2>t)throw new ug("argTypes array size mismatch! Must at least get return value and 'this' types!");
var v=null!==m[1]&&!1,z=Kg(m),O=!m[0].li,D=m[0],G=m[1];u=[r,vg,u,f,mg,D.Dg.bind(D),G?.Lg.bind(G)];for(D=2;D<t;++D)G=m[D],u.push(G.Lg.bind(G));if(!z)for(D=v?1:2;D<m.length;++D)null!==m[D].Og&&u.push(m[D].Og);z=Kg(m);D=m.length-2;var E=[];G=["fn"];v&&G.push("thisWired");for(t=0;t<D;++t)E.push(`arg${t}`),G.push(`arg${t}Wired`);E=E.join(",");G=G.join(",");E=`return function (${E}) {\n`;z&&(E+="var destructors = [];\n");var K=z?"destructors":"null",y="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");
v&&(E+=`var thisWired = toClassParamWire(${K}, this);\n`);for(t=0;t<D;++t){var W=`toArg${t}Wire`;E+=`var arg${t}Wired = ${W}(${K}, arg${t});\n`;y.push(W)}E+=(O||h?"var rv = ":"")+`invoker(${G});\n`;if(z)E+="runDestructors(destructors);\n";else for(t=v?1:2;t<m.length;++t)v=1===t?"thisWired":"arg"+(t-2)+"Wired",null!==m[t].Og&&(E+=`${v}_dtor(${v});\n`,y.push(`${v}_dtor`));O&&(E+="var ret = fromRetWire(rv);\nreturn ret;\n");m=(new Function(y,E+"}\n"))(...u);r=Gg(r,m);m=b-1;if(!g.hasOwnProperty(n))throw new rg("Replacing nonexistent public symbol");
void 0!==g[n].Qg&&void 0!==m?g[n].Qg[m]=r:(g[n]=r,g[n].bi=m);return[]})},fb=(a,b,c,d,e)=>{b=Q(b);let f=l=>l;if(0===d){var h=32-8*c;f=l=>l<<h>>>h;e=f(e)}sg(a,{name:b,Dg:f,Lg:(l,m)=>m,Tg:xg(b,c,0!==d),Og:null})},gb=(a,b,c)=>{function d(f){var h=(q(),C)[f>>2];f=(q(),C)[f+4>>2];return new e((q(),w).buffer,f,h)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=Q(c);sg(a,{name:c,Dg:d,Tg:d},{Ui:!0})},Rg=(a,b,c,d)=>{if(!(0<
d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;f++}}b[c]=0;return c-e},R=(a,b,c)=>Rg(a,(q(),x),b,c),Sg=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=
d&&57343>=d?(b+=4,++c):b+=3}return b},hb=(a,b)=>{b=Q(b);sg(a,{name:b,Dg(c){var d=(q(),C)[c>>2];d=P(c+4,d,!0);I(c);return d},Lg(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new ug("Cannot pass non-string to std::string");var f=e?Sg(d):d.length;var h=H(4+f+1),l=h+4;(q(),C)[h>>2]=f;e?R(d,l,f+1):(q(),x).set(d,l);null!==c&&c.push(I,h);return h},Tg:ng,Og(c){I(c)}})},Tg=globalThis.TextDecoder?new TextDecoder("utf-16le"):
void 0,Ug=(a,b,c)=>{a>>=1;b=ig((q(),Da),a,b/2,c);if(16<b-a&&Tg)return Tg.decode((q(),Da).slice(a,b));for(c="";a<b;++a){var d=(q(),Da)[a];c+=String.fromCharCode(d)}return c},Vg=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);(q(),A)[b>>1]=f;b+=2}(q(),A)[b>>1]=0;return b-d},Wg=a=>2*a.length,Xg=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=(q(),C)[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Yg=(a,b,
c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;(q(),B)[b>>2]=f;b+=4;if(b+4>c)break}(q(),B)[b>>2]=0;return b-d},Zg=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},ib=(a,b,c)=>{c=Q(c);if(2===b){var d=Ug;var e=Vg;var f=Wg}else d=Xg,e=Yg,f=Zg;sg(a,{name:c,Dg:h=>{var l=(q(),C)[h>>2];l=d(h+4,l*b,!0);I(h);return l},Lg:(h,l)=>{if("string"!=typeof l)throw new ug(`Cannot pass non-string to C++ string type ${c}`);
var m=f(l),n=H(4+m+b);(q(),C)[n>>2]=m/b;e(l,n+4,m+b);null!==h&&h.push(I,n);return n},Tg:ng,Og(h){I(h)}})},jb=(a,b,c,d,e,f)=>{lg[a]={name:Q(b),Yi:Ng(c,d),Zi:Ng(e,f),ii:[]}},kb=(a,b,c,d,e,f,h,l,m,n)=>{lg[a].ii.push({Ni:Q(b),Ri:c,Pi:Ng(d,e),Qi:f,ej:h,dj:Ng(l,m),fj:n})},lb=(a,b)=>{b=Q(b);sg(a,{li:!0,name:b,Dg:()=>{},Lg:()=>{}})},mb=(a,b)=>R("./this.program",a,b),nb=a=>{va(a,!ba,1,!aa,2097152,!1);xa()},$g=a=>{if(!(a instanceof Rf||"unwind"==a))throw a;},ah=()=>{if(!(Ia||0<J))try{k?Ef()&&Jf(ka):dd(ka)}catch(a){$g(a)}},
eg=a=>{if(!Ia&&!ja)try{a(),ah()}catch(b){$g(b)}},bh=!Atomics.waitAsync||globalThis.navigator?.userAgent&&91>Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2]),ya=a=>{if(!bh){var b=Atomics.waitAsync((q(),B),a>>2,a);b.async&&(b.value.then(Ba),a+=128,Atomics.store((q(),B),a>>2,1))}},Ba=()=>eg(()=>{var a=Ef();a&&(ya(a),Lf())}),ob=(a,b)=>{a==b?setTimeout(Ba):k?postMessage({Fh:a,Vg:"checkMailbox"}):(a=Xf[a])&&a.postMessage({Vg:"checkMailbox"})},ch=[],pb=(a,b,c,d,e)=>{d/=2;ch.length=
d;e>>=3;for(var f=0;f<d;f++)(q(),Fa)[e+2*f]?ch[f]=(q(),Fa)[e+2*f+1]:ch[f]=(q(),F)[e+2*f+1];a=b?dh[b]:eh[a];fg=c;c=a(...ch);fg=0;return c},qb=()=>{J=0},rb=a=>{k?postMessage({Vg:"cleanupThread",ij:a}):bg(Xf[a])},sb=()=>{},fh=[],gh=a=>{var b=fh.length;fh.push(a);return b},hh=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Ig((q(),C)[b+4*d>>2],`parameter ${d}`);return c},ih=(a,b,c)=>{var d=[];a=a(d,c);d.length&&((q(),C)[b>>2]=Bg(d));return a},jh={},kh=a=>{var b=jh[a];return void 0===b?Q(a):b},tb=(a,b,c)=>
{var [d,...e]=hh(a,b);b=d.Lg.bind(d);var f=e.map(m=>m.Tg.bind(m));a--;var h={toValue:Ag};a=f.map((m,n)=>{var r=`argFromPtr${n}`;h[r]=m;return`${r}(args${n?"+"+8*n:""})`});switch(c){case 0:var l="toValue(handle)";break;case 2:l="new (toValue(handle))";break;case 3:l="";break;case 1:h.getStringOrSymbol=kh,l="toValue(handle)[getStringOrSymbol(methodName)]"}l+=`(${a})`;d.li||(h.toReturnWire=b,h.emval_returnValue=ih,l=`return emval_returnValue(toReturnWire, destructorsRef, ${l})`);l=`return function (handle, methodName, destructorsRef, args) {\n  ${l}\n  }`;
c=(new Function(Object.keys(h),l))(...Object.values(h));l=`methodCaller<(${e.map(m=>m.name)}) => ${d.name}>`;return gh(Gg(l,c))},vb=a=>{if(!a)return Bg(globalThis);a=kh(a);return Bg(globalThis[a])},wb=(a,b)=>{a=Ag(a);b=Ag(b);return Bg(a[b])},xb=a=>{9<a&&(zg[a+1]+=1)},yb=(a,b,c,d,e)=>fh[a](b,c,d,e),zb=()=>Bg([]),Ab=a=>{a=Ag(a);for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return Bg(b)},Bb=a=>Bg(kh(a)),Cb=a=>{var b=Ag(a);mg(b);ub(a)},Db=a=>{a=Ag(a);return Bg(typeof a)};
function Eb(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);(q(),B)[b>>2]=a.getUTCSeconds();(q(),B)[b+4>>2]=a.getUTCMinutes();(q(),B)[b+8>>2]=a.getUTCHours();(q(),B)[b+12>>2]=a.getUTCDate();(q(),B)[b+16>>2]=a.getUTCMonth();(q(),B)[b+20>>2]=a.getUTCFullYear()-1900;(q(),B)[b+24>>2]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;(q(),B)[b+28>>2]=a}
var lh=a=>0===a%4&&(0!==a%100||0===a%400),mh=[0,31,60,91,121,152,182,213,244,274,305,335],nh=[0,31,59,90,120,151,181,212,243,273,304,334];
function Fb(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);(q(),B)[b>>2]=a.getSeconds();(q(),B)[b+4>>2]=a.getMinutes();(q(),B)[b+8>>2]=a.getHours();(q(),B)[b+12>>2]=a.getDate();(q(),B)[b+16>>2]=a.getMonth();(q(),B)[b+20>>2]=a.getFullYear()-1900;(q(),B)[b+24>>2]=a.getDay();var c=(lh(a.getFullYear())?mh:nh)[a.getMonth()]+a.getDate()-1|0;(q(),B)[b+28>>2]=c;(q(),B)[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),
0,1)).getTimezoneOffset();a=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;(q(),B)[b+32>>2]=a}
function Gb(a){var b=new Date((q(),B)[a+20>>2]+1900,(q(),B)[a+16>>2],(q(),B)[a+12>>2],(q(),B)[a+8>>2],(q(),B)[a+4>>2],(q(),B)[a>>2],0),c=(q(),B)[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),h=Math.min(f,e);0>c?(q(),B)[a+32>>2]=Number(e!=f&&h==d):0<c!=(h==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?h:e)-d)));(q(),B)[a+24>>2]=b.getDay();c=(lh(b.getFullYear())?mh:nh)[b.getMonth()]+b.getDate()-1|0;
(q(),B)[a+28>>2]=c;(q(),B)[a>>2]=b.getSeconds();(q(),B)[a+4>>2]=b.getMinutes();(q(),B)[a+8>>2]=b.getHours();(q(),B)[a+12>>2]=b.getDate();(q(),B)[a+16>>2]=b.getMonth();(q(),B)[a+20>>2]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)}var oh={},vc=()=>performance.timeOrigin+performance.now();
function Hb(a,b){if(k)return L(3,1,a,b);oh[a]&&(clearTimeout(oh[a].id),delete oh[a]);if(!b)return 0;var c=setTimeout(()=>{delete oh[a];eg(()=>Kf(a,performance.timeOrigin+performance.now()))},b);oh[a]={id:c,dk:b};return 0}
var Ib=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var h=Math.max(f,e);(q(),C)[a>>2]=60*h;(q(),B)[b>>2]=Number(f!=e);b=l=>{var m=Math.abs(l);return`UTC${0<=l?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(R(a,c,17),R(b,d,17)):(R(a,d,17),R(b,c,17))},Jb=(a,b)=>(q(),x).set(ph[a].Oi,b),qh=[],Kb=()=>qh.length,ph=[],Lb=()=>ph.length,Mb=(a,b)=>{a=qh[a].rj;R(a,b,Sg(a)+1)},
Nb=a=>ph[a].mode,Ob=a=>ph[a].Oi.length,Pb=(a,b)=>{a=qh[a].Xj;R(a,b,Sg(a)+1)},Qb=(a,b)=>{a=ph[a].Yj;R(a,b,Sg(a)+1)},rh=[],Rb=()=>{a:{if(!rh.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(Sg(a)+1);a=Rg(a,b,0,b.length);b.length=a;rh=b}b=rh.shift()}return"number"===typeof b?b:-1},Bh=(a,b)=>{sh=a;th=b;if(uh)if(vh||(J+=1,vh=!0),0==a)wh=function(){setTimeout(xh,Math.max(0,yh+b-(performance.timeOrigin+performance.now()))|0)};
else if(1==a)wh=function(){zh(xh)};else if(2==a){if(!Ah)if(globalThis.setImmediate)Ah=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ah=d=>{c.push(d);ba?(g.setImmediates??(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}wh=function(){Ah(xh)}}},Jh=(a,b,c,d,e)=>{function f(){return h<Ch?(--J,ah(),!1):!0}uh=a;Dh=d;var h=Ch;vh=!1;
xh=function(){if(!ja)if(0<Eh.length){var l=Eh.shift();l.Mj(l.zh);if(Fh){var m=Fh,n=0==m%1?m-1:Math.floor(m);Fh=l.sj?n:(8*m+(n+.5))/9}f()&&setTimeout(xh,0)}else if(f())if(Gh=Gh+1|0,1==sh&&1<th&&0!=Gh%th)wh();else{0==sh&&(yh=performance.timeOrigin+performance.now());a:if(!ja){for(l of Hh)if(!1===l())break a;eg(a);for(m of Ih)m()}f()&&wh()}};e||(0<b?Bh(0,1E3/b):Bh(1,1),wh());if(c)throw"unwind";},vh=!1,wh=null,Ch=0,uh=null,Dh=0,sh=0,th=0,Gh=0,Eh=[],Hh=[],Ih=[];function Kh(){wh=null;Ch++}var Lh=0;
function zh(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Lh)Lh=b+1E3/60;else for(;b+2>=Lh;)Lh+=1E3/60;setTimeout(a,Math.max(Lh-b,0))}}
var Mh={},yh,xh,Ah,Fh,Nh=25,Oh="Emscripten OpenAL",Ph={},Qh={},T=null,Rh={0:{id:0,sh:0,Cg:null,frequency:0,Yg:2,channels:1,length:0}},Sh=1,Th=[],Vh=a=>{if((1!==sh||"visible"==document.visibilityState)&&4114===a.state){for(var b=Uh(a),c=a.Jg,d=a.Ig,e=a.Gg,f=0;f<a.Fg.length;f++){var h=a.Fg[f];c=h.yh+h.ih;d=0;e+=h.$h+1}l||=.1;var l=b+l;for(b=0;c<l;){if(e>=a.Bg.length)if(a.Xg)e%=a.Bg.length;else break;f=a.Bg[e%a.Bg.length];if(0===f.length){if(b++,b===a.Bg.length)break}else{h=a.context.Ng.createBufferSource();
h.buffer=f.Cg;h.playbackRate.value=a.playbackRate;if(f.Cg.xh||f.Cg.wh)h.loopStart=f.Cg.xh,h.loopEnd=f.Cg.wh;if(4136===a.type&&a.Xg){var m=Number.POSITIVE_INFINITY;h.loop=!0;f.Cg.xh&&(h.loopStart=f.Cg.xh);f.Cg.wh&&(h.loopEnd=f.Cg.wh)}else m=(f.Cg.duration-d)/a.playbackRate;h.Ii=d;h.ih=m;h.$h=b;b=0;h.connect(a.gain);"undefined"!=typeof h.start?(c=Math.max(c,a.context.Ng.currentTime),h.start(c,d)):"undefined"!=typeof h.noteOn&&(c=Math.max(c,a.context.Ng.currentTime),h.noteOn(c));h.yh=c;a.Fg.push(h);
c+=m}d=0;e++}}},Uh=a=>{var b=a.context.Ng.currentTime;if(4114!==a.state)return b;isFinite(a.Jg)||(a.Jg=b-a.Ig/a.playbackRate,a.Ig=0);for(var c;a.Fg.length;){c=a.Fg[0];a.Gg+=c.$h;c=c.yh+c.ih;if(b<c)break;a.Fg.shift();a.Jg=c;a.Ig=0;a.Gg++}if(a.Gg>=a.Bg.length&&!a.Xg)Wh(a,4116);else if(4136===a.type&&a.Xg)if(c=a.Bg[0],0===c.length)a.Ig=0;else{var d=(b-a.Jg)*a.playbackRate,e=c.Cg.xh||0,f=c.Cg.wh||c.Cg.duration;f<=e&&(f=c.Cg.duration);d<f?a.Ig=d:a.Ig=e+(d-e)%(f-e)}else if(a.Fg[0])a.Ig=(b-a.Fg[0].yh)*a.playbackRate;
else for(4136!==a.type&&a.Xg&&(c=Xh(a)/a.playbackRate,0<c&&(a.Jg+=Math.floor((b-a.Jg)/c)*c)),d=0;d<a.Bg.length;d++){if(a.Gg>=a.Bg.length)if(a.Xg)a.Gg%=a.Bg.length;else{Wh(a,4116);break}c=a.Bg[a.Gg];if(0<c.length){c=a.Jg+c.Cg.duration/a.playbackRate;if(b<c){a.Ig=(b-a.Jg)*a.playbackRate;break}a.Jg=c}a.Ig=0;a.Gg++}return b},Yh=a=>{for(var b=0;b<a.Fg.length;b++)a.Fg[b].stop();a.Fg.length=0},Wh=(a,b)=>{if(4114===b){if(4114===a.state||4116==a.state)a.Gg=0,a.Ig=0;Yh(a);a.state=4114;a.Jg=Number.NEGATIVE_INFINITY;
Vh(a)}else 4115===b?4114===a.state&&(Uh(a),Yh(a),a.state=4115):4116===b?4113!==a.state&&(a.state=4116,a.Gg=a.Bg.length,a.Jg=Number.NEGATIVE_INFINITY,a.Ig=0,Yh(a)):4113===b&&4113!==a.state&&(a.state=4113,a.Gg=0,a.Jg=Number.NEGATIVE_INFINITY,a.Ig=0,Yh(a))},ai=a=>{if(4144!==a.type){for(var b=Rh[0],c=0;c<a.Bg.length;c++)if(0!==a.Bg[c].id){b=a.Bg[c];break}1===a.Sh||2===a.Sh&&1===b.channels?a.Eg||(a.Eg=a.context.Ng.createPanner(),Zh(a),$h(a),a.Eg.connect(a.context.gain),a.gain.disconnect(),a.gain.connect(a.Eg)):
a.Eg&&(a.Eg.disconnect(),a.gain.disconnect(),a.gain.connect(a.context.gain),a.Eg=null)}},bi=a=>{for(var b in a.sources)Zh(a.sources[b])},Zh=a=>{var b=a.Eg;if(b)switch(b.refDistance=a.refDistance,b.maxDistance=a.maxDistance,b.rolloffFactor=a.rolloffFactor,b.panningModel=a.context.ji?"HRTF":"equalpower",a.context.wi?a.distanceModel:a.context.distanceModel){case 0:b.distanceModel="inverse";b.refDistance=3.40282E38;break;case 53249:case 53250:b.distanceModel="inverse";break;case 53251:case 53252:b.distanceModel=
"linear";break;case 53253:case 53254:b.distanceModel="exponential"}},$h=a=>{if(a.Eg){var b=a.Eg,c=a.position[0],d=a.position[1],e=a.position[2],f=a.direction[0],h=a.direction[1],l=a.direction[2],m=a.context.listener,n=m.position[0],r=m.position[1],u=m.position[2];if(a.Rh){var t=-m.direction[0],v=-m.direction[1],z=-m.direction[2],O=m.Wh[0],D=m.Wh[1],G=m.Wh[2],E=(qa,ge,he)=>{qa=Math.sqrt(qa*qa+ge*ge+he*he);return qa<Number.EPSILON?0:1/qa},K=E(t,v,z);t*=K;v*=K;z*=K;K=E(O,D,G);O*=K;D*=K;G*=K;var y=D*
z-G*v,W=G*t-O*z,N=O*v-D*t;K=E(y,W,N);y*=K;W*=K;N*=K;O=v*N-z*W;D=z*y-t*N;G=t*W-v*y;E=f;K=h;var S=l;f=E*y+K*O+S*t;h=E*W+K*D+S*v;l=E*N+K*G+S*z;E=c;K=d;S=e;c=E*y+K*O+S*t+n;d=E*W+K*D+S*v+r;e=E*N+K*G+S*z+u}b.positionX?(c!=b.positionX.value&&(b.positionX.value=c),d!=b.positionY.value&&(b.positionY.value=d),e!=b.positionZ.value&&(b.positionZ.value=e)):b.setPosition(c,d,e);b.orientationX?(f!=b.orientationX.value&&(b.orientationX.value=f),h!=b.orientationY.value&&(b.orientationY.value=h),l!=b.orientationZ.value&&
(b.orientationZ.value=l)):b.setOrientation(f,h,l);b=a.ph;f=a.Ug[0];h=a.Ug[1];l=a.Ug[2];t=m.Ug[0];v=m.Ug[1];m=m.Ug[2];c===n&&d===r&&e===u||f===t&&h===v&&l===m?a.ph=1:(z=a.context.speedOfSound,O=a.context.dopplerFactor,c=n-c,d=r-d,e=u-e,u=Math.sqrt(c*c+d*d+e*e),a.ph=(z-O*Math.min((c*t+d*v+e*m)/u,z/O))/(z-O*Math.min((c*f+d*h+e*l)/u,z/O)));a.ph!==b&&ci(a)}},ci=a=>{if(4114===a.state){Uh(a);for(var b=1;b<a.Fg.length;b++)a.Fg[b].stop();1<a.Fg.length&&(a.Fg.length=1);if(b=a.Fg[0])b.ih=4136===a.type&&a.Xg?
Number.POSITIVE_INFINITY:(b.buffer.duration-b.Ii)/a.playbackRate,b.playbackRate.value=a.playbackRate,Vh(a)}},Xh=a=>{for(var b=0,c=0;c<a.Bg.length;c++){var d=a.Bg[c].Cg;b+=d?d.duration:0}return b},di=(a,b)=>{var c=4114==a.state;c&&Wh(a,4113);if(null!==a.Bg[a.Gg].Cg){for(a.Gg=0;b>a.Bg[a.Gg].Cg.duration;)b-=a.Bg[a.Gg].Cg.duration,a.Gg++;a.Ig=b}c&&Wh(a,4114)},ei=(a,b,c)=>{if(T)if(a=T.sources[a])if(null===c)T.Ag=40962;else switch(b){case 514:1===c?(a.Rh=!0,$h(a)):0===c?(a.Rh=!1,$h(a)):T.Ag=40963;break;
case 4097:if(!Number.isFinite(c)){T.Ag=40963;break}a.coneInnerAngle=c;a.Eg&&(a.Eg.coneInnerAngle=c%360);break;case 4098:if(!Number.isFinite(c)){T.Ag=40963;break}a.coneOuterAngle=c;a.Eg&&(a.Eg.coneOuterAngle=c%360);break;case 4099:if(!Number.isFinite(c)||0>=c){T.Ag=40963;break}if(a.pitch===c)break;a.pitch=c;ci(a);break;case 4100:if(!Number.isFinite(c[0])||!Number.isFinite(c[1])||!Number.isFinite(c[2])){T.Ag=40963;break}a.position[0]=c[0];a.position[1]=c[1];a.position[2]=c[2];$h(a);break;case 4101:if(!Number.isFinite(c[0])||
!Number.isFinite(c[1])||!Number.isFinite(c[2])){T.Ag=40963;break}a.direction[0]=c[0];a.direction[1]=c[1];a.direction[2]=c[2];$h(a);break;case 4102:if(!Number.isFinite(c[0])||!Number.isFinite(c[1])||!Number.isFinite(c[2])){T.Ag=40963;break}a.Ug[0]=c[0];a.Ug[1]=c[1];a.Ug[2]=c[2];$h(a);break;case 4103:if(1===c)a.Xg=!0,Uh(a),4136===a.type&&0<a.Fg.length&&(c=a.Fg[0],c.loop=!0,c.ih=Number.POSITIVE_INFINITY);else if(0===c){a.Xg=!1;var d=Uh(a);4136===a.type&&0<a.Fg.length&&(c=a.Fg[0],c.loop=!1,c.ih=a.Bg[0].Cg.duration/
a.playbackRate,c.yh=d-a.Ig/a.playbackRate)}else T.Ag=40963;break;case 4105:if(4114===a.state||4115===a.state){T.Ag=40964;break}if(0===c){for(d in a.Bg)a.Bg[d].sh--;a.Bg.length=1;a.Bg[0]=Rh[0];a.Gg=0;a.type=4144}else{var e=Rh[c];if(!e){T.Ag=40963;break}for(d in a.Bg)a.Bg[d].sh--;a.Bg.length=0;e.sh++;a.Bg=[e];a.Gg=0;a.type=4136}ai(a);Vh(a);break;case 4106:if(!Number.isFinite(c)||0>c){T.Ag=40963;break}a.gain.gain.value=c;break;case 4109:if(!Number.isFinite(c)||0>c||c>Math.min(a.ni,1)){T.Ag=40963;break}a.oi=
c;break;case 4110:if(!Number.isFinite(c)||c<Math.max(0,a.oi)||1<c){T.Ag=40963;break}a.ni=c;break;case 4128:if(!Number.isFinite(c)||0>c){T.Ag=40963;break}a.refDistance=c;a.Eg&&(a.Eg.refDistance=c);break;case 4129:if(!Number.isFinite(c)||0>c){T.Ag=40963;break}a.rolloffFactor=c;a.Eg&&(a.Eg.rolloffFactor=c);break;case 4130:if(!Number.isFinite(c)||0>c||1<c){T.Ag=40963;break}a.coneOuterGain=c;a.Eg&&(a.Eg.coneOuterGain=c);break;case 4131:if(!Number.isFinite(c)||0>c){T.Ag=40963;break}a.maxDistance=c;a.Eg&&
(a.Eg.maxDistance=c);break;case 4132:if(0>c||c>Xh(a)){T.Ag=40963;break}di(a,c);break;case 4133:d=Xh(a);if(0<d){for(var f in a.Bg)if(f){e=a.Bg[f].frequency;break}c/=e}if(0>c||c>d){T.Ag=40963;break}di(a,c);break;case 4134:d=Xh(a);if(0<d){for(f in a.Bg)if(f){e=a.Bg[f];var h=e.frequency*e.Yg*e.channels;break}c/=h}if(0>c||c>d){T.Ag=40963;break}di(a,c);break;case 4628:if(0!==c&&1!==c&&2!==c){T.Ag=40963;break}a.Sh=c;ai(a);break;case 8201:case 8202:case 8203:T.Ag=40964;break;case 53248:switch(c){case 0:case 53249:case 53250:case 53251:case 53252:case 53253:case 53254:a.distanceModel=
c;T.wi&&bi(T);break;default:T.Ag=40963}break;default:T.Ag=40962}else T.Ag=40961};
function Tb(a,b,c,d,e){if(k)return L(4,1,a,b,c,d,e);if(T)if(a=Rh[a])if(0>=e)T.Ag=40963;else{var f=null;try{switch(b){case 4352:if(0<d){f=T.Ng.createBuffer(1,d,e);for(var h=f.getChannelData(0),l=0;l<d;++l)h[l]=.0078125*(q(),x)[c++]-1}a.Yg=1;a.channels=1;a.length=d;break;case 4353:if(0<d)for(f=T.Ng.createBuffer(1,d>>1,e),h=f.getChannelData(0),c>>=1,l=0;l<d>>1;++l)h[l]=3.0517578125E-5*(q(),A)[c++];a.Yg=2;a.channels=1;a.length=d>>1;break;case 4354:if(0<d){f=T.Ng.createBuffer(2,d>>1,e);h=f.getChannelData(0);
var m=f.getChannelData(1);for(l=0;l<d>>1;++l)h[l]=.0078125*(q(),x)[c++]-1,m[l]=.0078125*(q(),x)[c++]-1}a.Yg=1;a.channels=2;a.length=d>>1;break;case 4355:if(0<d)for(f=T.Ng.createBuffer(2,d>>2,e),h=f.getChannelData(0),m=f.getChannelData(1),c>>=1,l=0;l<d>>2;++l)h[l]=3.0517578125E-5*(q(),A)[c++],m[l]=3.0517578125E-5*(q(),A)[c++];a.Yg=2;a.channels=2;a.length=d>>2;break;case 65552:if(0<d)for(f=T.Ng.createBuffer(1,d>>2,e),h=f.getChannelData(0),c>>=2,l=0;l<d>>2;++l)h[l]=(q(),Ea)[c++];a.Yg=4;a.channels=1;
a.length=d>>2;break;case 65553:if(0<d)for(f=T.Ng.createBuffer(2,d>>3,e),h=f.getChannelData(0),m=f.getChannelData(1),c>>=2,l=0;l<d>>3;++l)h[l]=(q(),Ea)[c++],m[l]=(q(),Ea)[c++];a.Yg=4;a.channels=2;a.length=d>>3;break;default:T.Ag=40963;return}a.frequency=e;a.Cg=f}catch(n){T.Ag=40963}}else T.Ag=40963}
function Ub(a,b){if(k)return L(5,1,a,b);if(T){for(var c=0;c<a;++c){var d=(q(),B)[b+4*c>>2];if(0!==d){if(!Rh[d]){T.Ag=40961;return}if(Rh[d].sh){T.Ag=40964;return}}}for(c=0;c<a;++c)d=(q(),B)[b+4*c>>2],0!==d&&(Ph[Rh[d].deviceId]--,delete Rh[d],Th.push(d))}}function Zb(a,b,c){if(k)return L(7,1,a,b,c);switch(b){case 514:case 4097:case 4098:case 4103:case 4105:case 4128:case 4129:case 4131:case 4132:case 4133:case 4134:case 4628:case 8201:case 8202:case 53248:ei(a,b,c);break;default:ei(a,b,null)}}
function Vb(a,b){if(k)return L(6,1,a,b);if(T){for(var c=0;c<a;++c){var d=(q(),B)[b+4*c>>2];if(!T.sources[d]){T.Ag=40961;return}}for(c=0;c<a;++c)d=(q(),B)[b+4*c>>2],Wh(T.sources[d],4116),Zb(d,4105,0),delete T.sources[d],Th.push(d)}}function Wb(a,b){if(k)return L(8,1,a,b);if(T)for(var c=0;c<a;++c){var d={deviceId:T.deviceId,id:0<Th.length?Th.pop():Sh++,sh:0,Cg:null,frequency:0,Yg:2,channels:1,length:0};Ph[d.deviceId]++;Rh[d.id]=d;(q(),B)[b+4*c>>2]=d.id}}
function Xb(a,b){if(k)return L(9,1,a,b);if(T)for(var c=0;c<a;++c){var d=T.Ng.createGain();d.connect(T.gain);d={context:T,id:0<Th.length?Th.pop():Sh++,type:4144,state:4113,Bg:[Rh[0]],Fg:[],Xg:!1,pitch:1,ph:1,gain:d,oi:0,ni:1,Eg:null,Gg:0,Jg:Number.NEGATIVE_INFINITY,Ig:0,Rh:!1,refDistance:1,maxDistance:3.40282E38,rolloffFactor:1,position:[0,0,0],Ug:[0,0,0],direction:[0,0,0],coneOuterGain:0,coneInnerAngle:360,coneOuterAngle:360,distanceModel:53250,Sh:2,get playbackRate(){return this.pitch*this.ph}};
T.sources[d.id]=d;(q(),B)[b+4*c>>2]=d.id}}function Yb(a){if(k)return L(10,1,a);T&&((a=T.sources[a])?Wh(a,4114):T.Ag=40961)}function $b(a){if(k)return L(11,1,a);if(!(a in Ph)||0<Ph[a])return 0;delete Ph[a];Th.push(a);return 1}var fi=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,document.getElementById("canvas")])c?.addEventListener(b,()=>{"suspended"===a.state&&a.resume()},{once:!0})};
function ac(a,b){if(k)return L(12,1,a,b);if(!(a in Ph))return 0;var c=null,d=[],e=null;if(b>>=2)for(var f=0,h=0;;){f=(q(),B)[b++];d.push(f);if(0===f)break;h=(q(),B)[b++];d.push(h);switch(f){case 4103:c||={};c.sampleRate=h;break;case 4112:case 4113:break;case 6546:switch(h){case 0:e=!1;break;case 1:e=!0;break;case 2:break;default:return 0}break;case 6550:if(0!==h)return 0;break;default:return 0}}f=window.AudioContext||window.webkitAudioContext;b=null;try{b=c?new f(c):new f}catch(n){return 0}fi(b);
"undefined"==typeof b.createGain&&(b.createGain=b.createGainNode);c=b.createGain();c.connect(b.destination);var l={deviceId:a,id:0<Th.length?Th.pop():Sh++,oj:d,Ng:b,listener:{position:[0,0,0],Ug:[0,0,0],direction:[0,0,0],Wh:[0,0,0]},sources:[],interval:setInterval(()=>{var n=l;if(1!==sh||"visible"==document.visibilityState)for(var r in n.sources)Vh(n.sources[r])},Nh),gain:c,distanceModel:53250,speedOfSound:343.3,dopplerFactor:1,wi:!1,ji:e||!1,Hh:0,get Ag(){return this.Hh},set Ag(n){if(0===this.Hh||
0===n)this.Hh=n}};Ph[a]++;Qh[l.id]=l;if(null!==e)for(var m in Qh)d=Qh[m],d.deviceId===a&&(d.ji=e,bi(d));return l.id}function bc(a){if(k)return L(13,1,a);var b=Qh[a];T!==b&&(Qh[a].interval&&clearInterval(Qh[a].interval),Ph[b.deviceId]--,delete Qh[a],Th.push(a))}function cc(a){if(k)return L(14,1,a);0===a?T=null:T=Qh[a];return 1}function dc(a){return k?L(15,1,a):a&&P(a)!==Oh?0:globalThis.AudioContext||globalThis.webkitAudioContext?(a=0<Th.length?Th.pop():Sh++,Ph[a]=0,a):0}var lc=()=>Date.now(),gi=1;
function ec(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(gi)a=performance.timeOrigin+performance.now();else return 52;a=Math.round(1E6*a);(q(),Fa)[c>>3]=BigInt(a);return 0}
var hi=[],hc=(a,b,c)=>{hi.length=0;for(var d;d=(q(),x)[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;hi.push(112==d?(q(),C)[c>>2]:106==d?(q(),Fa)[c>>3]:105==d?(q(),B)[c>>2]:(q(),F)[c>>3]);c+=e?8:4}return dh[a](...hi)},ii=(a,b)=>{J+=1;setTimeout(()=>{--J;eg(a)},b)},ji=a=>{J+=1;zh(()=>{--J;eg(a)})},ic=(a,b,c)=>{var d=()=>M(a)(b);0<=c?ii(d,c):ji(d)},jc=()=>{Kh();uh=null},kc=()=>{},mc=a=>p(P(a)),nc=(a,b)=>p(P(a,b)),oc=()=>{J+=1;throw"unwind";};
function pc(a){if(ki.has(a)){var b=ki.get(a),c=ki;c.Mg[a]=void 0;c.Yh.push(a);0<b.readyState&&4>b.readyState&&b.abort()}}function qc(a){if(k)return L(16,1,a);J=0;dd(a)}
var U,li=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");return(a.getSupportedExtensions()||
[]).filter(c=>b.includes(c))},mi=1,ni=[],oi=[],pi=[],qi=[],ri=[],si=[],ti=[],ui={},dg={},vi=[1,1,2,2,4,4,4,2,3,4,8],wi=4,xi=0,yi=a=>{for(var b=mi++,c=a.length;c<b;c++)a[c]=null;for(;a[b];)b=mi++;return b},zi=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=U[c](),h=f&&yi(d);f?(f.name=h,d[h]=f):V||=1282;(q(),B)[b+4*e>>2]=h}},Ai=a=>{a=32-Math.clz32(0===a?0:a-1);var b=X.eh[a];if(b)return b;b=U.getParameter(34965);X.eh[a]=U.createBuffer();U.bindBuffer(34963,X.eh[a]);U.bufferData(34963,1<<a,35048);U.bindBuffer(34963,
b);return X.eh[a]},Ci=a=>{Bi=!1;for(var b=0;b<X.Oh;++b){var c=X.jh[b];if(c.Ah&&c.enabled){Bi=!0;var d=c.size;var e=c.type,f=c.stride;d=0<f?a*f:d*vi[e-5120]*a;e=32-Math.clz32(0===d?0:d-1);f=X.fh[e];var h=X.$g[e];X.$g[e]=X.$g[e]+1&63;var l=f[h];l?e=l:(l=U.getParameter(34964),f[h]=U.createBuffer(),U.bindBuffer(34962,f[h]),U.bufferData(34962,1<<e,35048),U.bindBuffer(34962,l),e=f[h]);U.bindBuffer(34962,e);U.bufferSubData(34962,0,(q(),x).subarray(c.Qh,c.Qh+d));c.Ci.call(U,b,c.size,c.type,c.pi,c.stride,
0)}}},cg={},V,X,Bi,Di=[0,globalThis.document??0,globalThis.window??0],Ei=a=>{a=2<a?P(a):a;return dg[a.slice(1)]||"canvas"==a&&Object.values(dg)[0]||Di[a]||globalThis.document?.querySelector(a)},Fi=(a,b,c)=>{var d=Ei(a);if(!d)return-4;if(d.Hg)a=(q(),B)[d.Hg>>2],d=(q(),B)[d.Hg+4>>2],(q(),B)[b>>2]=a,(q(),B)[c>>2]=d;else if(d.Rg)(q(),B)[b>>2]=d.Rg.width,(q(),B)[c>>2]=d.Rg.height;else{if(d.kh)return-4;(q(),B)[b>>2]=d.width;(q(),B)[c>>2]=d.height}return 0};
function Gi(a,b,c){return k?L(17,1,a,b,c):Fi(a,b,c)}var rc=(a,b,c)=>Ei(a)?Fi(a,b,c):Gi(a,b,c);function sc(){return k?L(18,1):devicePixelRatio}var Hi=a=>{a=2<a?P(a):a;return Di[a]||globalThis.document?.querySelector(a)},Ii=a=>0>Di.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};function tc(a,b,c){if(k)return L(19,1,a,b,c);a=Hi(a);if(!a)return-4;a=Ii(a);(q(),F)[b>>3]=a.width;(q(),F)[c>>3]=a.height;return 0}var uc=()=>/iPad|iPhone|iPod/.test(navigator.userAgent)?536870912:2147483648,Ji={};
function Ki(a,b){var c=Ji[a];if(c)b(null,c);else{try{var d=indexedDB.open(a,22)}catch(e){b(e);return}d.onupgradeneeded=e=>{var f=e.target.result;e=e.target.transaction;f.objectStoreNames.contains("FILE_DATA")?e.objectStore("FILE_DATA"):f.createObjectStore("FILE_DATA")};d.onsuccess=()=>{c=d.result;Ji[a]=c;b(null,c)};d.onerror=function(e){b(e.target.error||"unknown error");e.preventDefault()}}}
function Li(a,b,c){Ki(a,(d,e)=>{if(d)return c(d);d=e.transaction(["FILE_DATA"],b);d.onerror=f=>{c(f.target.error||"unknown error");f.preventDefault()};d=d.objectStore("FILE_DATA");c(null,d)})}function Mi(a,b,c){Li(a,"readonly",(d,e)=>{if(d)return c(d);d=e.get(b);d.onsuccess=f=>(f=f.target.result)?c(null,f):c(`file ${b} not found`);d.onerror=c})}function Ni(a,b,c,d){Li(a,"readwrite",(e,f)=>{if(e)return d(e);e=f.put(c,b);e.onsuccess=()=>d();e.onerror=d})}
function Oi(a,b,c){Li(a,"readwrite",(d,e)=>{if(d)return c(d);d=e.delete(b);d.onsuccess=()=>c();d.onerror=c})}function Pi(a,b,c){Li(a,"readonly",(d,e)=>{if(d)return c(d);d=e.count(b);d.onsuccess=f=>c(null,0<f.target.result);d.onerror=c})}
var wc=(a,b,c,d,e)=>{J+=1;Oi(P(a),P(b),f=>{--J;eg(()=>{f?e&&M(e)(c):d&&M(d)(c)})})},xc=(a,b,c,d,e)=>{J+=1;Pi(P(a),P(b),(f,h)=>{--J;eg(()=>{f?e&&M(e)(c):d&&M(d)(c,h)})})},yc=(a,b,c,d,e)=>{J+=1;Mi(P(a),P(b),(f,h)=>{--J;eg(()=>{if(f)e&&M(e)(c);else{var l=H(h.length);(q(),x).set(h,l);M(d)(c,l,h.length);I(l)}})})},zc=(a,b,c,d,e,f,h)=>{J+=1;Ni(P(a),P(b),new Uint8Array((q(),x).subarray(c,c+d)),l=>{--J;eg(()=>{l?h&&M(h)(e):f&&M(f)(e)})})},Ac=()=>navigator.hardwareConcurrency,Bc=a=>ha(P(a)),Qi={},Ri=a=>{var b=
Sg(a)+1,c=H(b);c&&R(a,c,b);return c},Si=a=>{var b;return(b=/\bwasm-function\[\d+\]:(0x[0-9a-f]+)/.exec(a))?+b[1]:(b=/:(\d+):\d+(?:\)|$)/.exec(a))?2147483648|+b[1]:0},Ti=a=>{for(var b of a)(a=Si(b))&&(Qi[a]=b)},Sc=()=>{var a=Error().stack.toString().split("\n");"Error"==a[0]&&a.shift();Ti(a);Qi.mi=Si(a[3]);Qi.Wi=a;return Qi.mi},Cc=a=>{a=Qi[a];if(!a)return 0;var b;if(b=/^\s+at .*\.wasm\.(.*) \(.*\)$/.exec(a))a=b[1];else if(b=/^\s+at (.*) \(.*\)$/.exec(a))a=b[1];else if(b=/^(.+?)@/.exec(a))a=b[1];else return 0;
I(Cc.ui??0);Cc.ui=Ri(a);return Cc.ui},Dc=(a,b)=>{function c(d){M(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ec=a=>{var b=(q(),x).length;a>>>=0;if(a<=b)return!1;var c=/iPad|iPhone|iPod/.test(navigator.userAgent)?536870912:2147483648;if(a>c)return!1;for(var d=1;4>=d;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);a:{e=(Math.min(c,65536*Math.ceil(Math.max(a,e)/65536))-la.buffer.byteLength+65535)/65536|0;try{la.grow(e);ma();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},
Ui=(a,b,c)=>{var d=Ei(a);if(!d)return-4;d.Hg&&((q(),B)[d.Hg>>2]=b,(q(),B)[d.Hg+4>>2]=c);if(d.Rg||!d.kh)d.Rg&&(d=d.Rg),a=!1,d.vh?.Pg&&(a=d.vh.Pg.getParameter(2978),a=a instanceof Int32Array&&4===a.length?0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height:!0),d.width=b,d.height=c,a&&d.vh.Pg.viewport(0,0,b,c);else{if(d.Hg){d=(q(),C)[d.Hg+8>>2];a=a?P(a):"";var e=0;a&&(e=Ri(a));Cf(d,e,b,c);return 1}return-4}return 0};function Vi(a,b,c){return k?L(20,1,a,b,c):Ui(a,b,c)}
var Fc=(a,b,c)=>Ei(a)?Ui(a,b,c):Vi(a,b,c),ag=[];function Wi(a){var b=Y.Kg[a];b.target.removeEventListener(b.Wg,b.gi,b.gh);Y.Kg.splice(a,1)}function Xi(){if(navigator.userActivation?navigator.userActivation.isActive:Y.Lh&&Y.Ki.Ih){var a=Y.Zg;Y.Zg=[];for(var b of a)b.Th(...b.ci)}}
function Yi(a){if(!a.target)return-4;if(a.ah)a.gi=function(c){++Y.Lh;Y.Ki=a;Xi();a.qh(c);Xi();--Y.Lh},a.target.addEventListener(a.Wg,a.gi,a.gh),Y.Kg.push(a),Y.bj||(ag.push(Y.$i),Y.bj=!0);else for(var b=0;b<Y.Kg.length;++b)Y.Kg[b].target==a.target&&Y.Kg[b].Wg==a.Wg&&Wi(b--);return 0}function Zi(a){switch(a){case 1:return 0;case 2:return fg;default:return a}}
var Y={qj:0,Nj:0,Mh:0,rh:0,Xh:0,ek:0,Hj:0,vj:0,Wj:0,oh:0,Lj:0,Zj:0,fk:0,Uh:0,$i(){for(;Y.Kg.length;)Wi(Y.Kg.length-1);Y.Zg=[]},Lh:0,Zg:[],uj(a,b,c){function d(f,h){if(f.length!=h.length)return!1;for(var l in f)if(f[l]!=h[l])return!1;return!0}for(var e of Y.Zg)if(e.Th==a&&d(e.ci,c))return;Y.Zg.push({Th:a,ti:b,ci:c});Y.Zg.sort((f,h)=>f.ti<h.ti)},ak(a){Y.Zg=Y.Zg.filter(b=>b.Th!=a)},Kg:[],aj:(a,b)=>{for(var c=0;c<Y.Kg.length;++c)Y.Kg[c].target!=a||b&&b!=Y.Kg[c].Wg||Wi(c--)},bk(a){let b=!1;for(let c=0;c<
Y.Kg.length;++c){const d=Y.Kg[c];d.target===a.target&&d.bh===a.bh&&d.ah===a.ah&&d.hh===a.hh&&(Wi(c--),b=!0)}return b?0:-5},Pj(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},$i=(a,b,c,d)=>{d=Zi(d);Y.oh||(Y.oh=H(80));b={target:Hi(2),Wg:"devicemotion",bh:17,hh:a,ah:c,qh:e=>{var f=Y.oh,h=e.acceleration,l=e.accelerationIncludingGravity,m=e.rotationRate;var n=0|(h&&1)|(l&&2)|(m&&4);h=h||{};
l=l||{};m=m||{};(q(),B)[f+72>>2]=n;(q(),F)[f>>3]=h.x;(q(),F)[f+8>>3]=h.y;(q(),F)[f+16>>3]=h.z;(q(),F)[f+24>>3]=l.x;(q(),F)[f+32>>3]=l.y;(q(),F)[f+40>>3]=l.z;(q(),F)[f+48>>3]=m.alpha;(q(),F)[f+56>>3]=m.beta;(q(),F)[f+64>>3]=m.gamma;d?Bf(d,c,17,Y.oh,80,a):M(c)(17,Y.oh,a)&&e.preventDefault()},gh:b};return Yi(b)};function Gc(a,b,c,d){return k?L(21,1,a,b,c,d):$i(a,b,c,d)}
var aj=(a,b,c,d,e,f,h)=>{h=Zi(h);Y.Mh||(Y.Mh=H(160));a={target:Hi(a),Wg:f,bh:e,hh:b,ah:d,qh:l=>{var m=Y.Mh;(q(),F)[m>>3]=l.timeStamp;var n=m>>2;(q(),B)[n+2]=l.location;(q(),w)[m+12]=l.ctrlKey;(q(),w)[m+13]=l.shiftKey;(q(),w)[m+14]=l.altKey;(q(),w)[m+15]=l.metaKey;(q(),w)[m+16]=l.repeat;(q(),B)[n+5]=l.charCode;(q(),B)[n+6]=l.keyCode;(q(),B)[n+7]=l.which;R(l.key||"",m+32,32);R(l.code||"",m+64,32);R(l.char||"",m+96,32);R(l.locale||"",m+128,32);h?Bf(h,d,e,m,160,b):M(d)(e,m,b)&&l.preventDefault()},gh:c};
return Yi(a)};function Hc(a,b,c,d,e){return k?L(22,1,a,b,c,d,e):aj(a,b,c,d,2,"keydown",e)}function Ic(a,b,c,d,e){return k?L(23,1,a,b,c,d,e):aj(a,b,c,d,3,"keyup",e)}
var Jc=(a,b,c)=>{a=M(a);Jh(a,b,c)},Kc=(a,b,c,d)=>{Jh(()=>M(a)(b),c,d,b)},bj=(a,b,c)=>{(q(),F)[a>>3]=b.timeStamp;var d=a>>2;(q(),B)[d+2]=b.screenX;(q(),B)[d+3]=b.screenY;(q(),B)[d+4]=b.clientX;(q(),B)[d+5]=b.clientY;(q(),w)[a+24]=b.ctrlKey;(q(),w)[a+25]=b.shiftKey;(q(),w)[a+26]=b.altKey;(q(),w)[a+27]=b.metaKey;(q(),A)[2*d+14]=b.button;(q(),A)[2*d+15]=b.buttons;(q(),B)[d+8]=b.movementX;(q(),B)[d+9]=b.movementY;a=Ii(c);(q(),B)[d+10]=b.clientX-(a.left|0);(q(),B)[d+11]=b.clientY-(a.top|0)},cj=(a,b,c,d,
e,f,h)=>{h=Zi(h);Y.rh||(Y.rh=H(64));a=Hi(a);return Yi({target:a,Ih:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Wg:f,bh:e,hh:b,ah:d,qh:l=>{bj(Y.rh,l,a);h?Bf(h,d,e,Y.rh,64,b):M(d)(e,Y.rh,b)&&l.preventDefault()},gh:c})};function Lc(a,b,c,d,e){return k?L(24,1,a,b,c,d,e):cj(a,b,c,d,5,"mousedown",e)}function Mc(a,b,c,d,e){return k?L(25,1,a,b,c,d,e):cj(a,b,c,d,8,"mousemove",e)}function Nc(a,b,c,d,e){return k?L(26,1,a,b,c,d,e):cj(a,b,c,d,6,"mouseup",e)}
var dj=(a,b,c,d,e,f,h)=>{h=Zi(h);Y.Uh||(Y.Uh=H(1552));a=Hi(a);return Yi({target:a,Ih:"touchstart"==f||"touchend"==f,Wg:f,bh:e,hh:b,ah:d,qh:l=>{var m={},n=l.touches;for(var r of n)r.ki=r.ri=0,m[r.identifier]=r;for(var u of l.changedTouches)u.ki=1,m[u.identifier]=u;for(var t of l.targetTouches)m[t.identifier].ri=1;n=Y.Uh;(q(),F)[n>>3]=l.timeStamp;(q(),w)[n+12]=l.ctrlKey;(q(),w)[n+13]=l.shiftKey;(q(),w)[n+14]=l.altKey;(q(),w)[n+15]=l.metaKey;r=n+16;u=Ii(a);t=0;for(let v of Object.values(m))if(m=r>>2,
(q(),B)[m]=v.identifier,(q(),B)[m+1]=v.screenX,(q(),B)[m+2]=v.screenY,(q(),B)[m+3]=v.clientX,(q(),B)[m+4]=v.clientY,(q(),B)[m+5]=v.pageX,(q(),B)[m+6]=v.pageY,(q(),w)[r+28]=v.ki,(q(),w)[r+29]=v.ri,(q(),B)[m+8]=v.clientX-(u.left|0),(q(),B)[m+9]=v.clientY-(u.top|0),r+=48,31<++t)break;(q(),B)[n+8>>2]=t;h?Bf(h,d,e,n,1552,b):M(d)(e,n,b)&&l.preventDefault()},gh:c})};function Oc(a,b,c,d,e){return k?L(27,1,a,b,c,d,e):dj(a,b,c,d,23,"touchend",e)}
function Pc(a,b,c,d,e){return k?L(28,1,a,b,c,d,e):dj(a,b,c,d,24,"touchmove",e)}function Qc(a,b,c,d,e){return k?L(29,1,a,b,c,d,e):dj(a,b,c,d,22,"touchstart",e)}var ej=(a,b,c,d,e)=>{e=Zi(e);Y.Xh||(Y.Xh=H(96));return Yi({target:a,Ih:!0,Wg:"wheel",bh:9,hh:b,ah:d,qh:f=>{var h=Y.Xh;bj(h,f,a);(q(),F)[h+64>>3]=f.deltaX;(q(),F)[h+72>>3]=f.deltaY;(q(),F)[h+80>>3]=f.deltaZ;(q(),B)[h+88>>2]=f.deltaMode;e?Bf(e,d,9,h,96,b):M(d)(9,h,b)&&f.preventDefault()},gh:c})};
function Rc(a,b,c,d,e){return k?L(30,1,a,b,c,d,e):(a=Hi(a))?"undefined"!=typeof a.onwheel?ej(a,b,c,d,e):-1:-4}var Tc=(a,b,c)=>{if(Qi.mi==a)var d=Qi.Wi;else d=Error().stack.toString().split("\n"),"Error"==d[0]&&d.shift(),Ti(d);for(var e=3;d[e]&&Si(d[e])!=a;)++e;for(a=0;a<c&&d[a+e];++a)(q(),B)[b+4*a>>2]=Si(d[a+e]);return a};function fj(a){var b=ki,c=b.Yh.pop()||b.Mg.length;b.Mg[c]=a;return c}class gj{Mg=[void 0];Yh=[];get(a){return this.Mg[a]}has(a){return void 0!==this.Mg[a]}}var ki;
function hj(a,b,c,d,e){function f(){var N=0,S=0;y.response&&G&&0===(q(),C)[a+12>>2]&&(S=y.response.byteLength);0<S&&(N=Ff((q(),C)[a+12>>2],S),(q(),x).set(new Uint8Array(y.response),N));(q(),C)[a+12>>2]=N;ij(a+16,S);ij(a+24,0);(N=y.response?y.response.byteLength:0)&&ij(a+32,N);(q(),A)[a+40>>1]=y.readyState;(q(),A)[a+42>>1]=y.status;y.statusText&&R(y.statusText,a+44,64);K&&(N=Ri(y.responseURL),(q(),C)[a+200>>2]=N)}var h=(q(),C)[a+8>>2];if(h){var l=P(h),m=a+108,n=P(m+0);n||="GET";var r=(q(),C)[m+56>>
2],u=(q(),C)[m+68>>2],t=(q(),C)[m+72>>2];h=(q(),C)[m+76>>2];var v=(q(),C)[m+80>>2],z=(q(),C)[m+84>>2],O=(q(),C)[m+88>>2],D=(q(),C)[m+52>>2],G=!!(D&1),E=!!(D&2),K=!!(D&64);u=u?P(u):void 0;t=t?P(t):void 0;var y=new XMLHttpRequest;y.withCredentials=!!(q(),x)[m+60];y.open(n,l,!K,u,t);K||(y.timeout=r);y.Mg=l;y.responseType="arraybuffer";v&&(l=P(v),y.overrideMimeType(l));if(h)for(;;){m=(q(),C)[h>>2];if(!m)break;l=(q(),C)[h+4>>2];if(!l)break;h+=8;m=P(m);l=P(l);y.setRequestHeader(m,l)}var W=fj(y);(q(),C)[a>>
2]=W;h=z&&O?(q(),x).slice(z,z+O):null;y.onload=N=>{ki.has(W)&&(f(),200<=y.status&&300>y.status?b(a,y,N):c(a,N))};y.onerror=N=>{ki.has(W)&&(f(),c(a,N))};y.ontimeout=N=>{ki.has(W)&&c(a,N)};y.onprogress=N=>{if(ki.has(W)){var S=G&&E&&y.response?y.response.byteLength:0,qa=0;0<S&&G&&E&&(qa=Ff((q(),C)[a+12>>2],S),(q(),x).set(new Uint8Array(y.response),qa));(q(),C)[a+12>>2]=qa;ij(a+16,S);ij(a+24,N.loaded-S);ij(a+32,N.total);(q(),A)[a+40>>1]=y.readyState;S=y.status;3<=y.readyState&&0===y.status&&0<N.loaded&&
(S=200);(q(),A)[a+42>>1]=S;y.statusText&&R(y.statusText,a+44,64);d(a,N)}};y.onreadystatechange=N=>{if(ki.has(W)){(q(),A)[a+40>>1]=y.readyState;2<=y.readyState&&((q(),A)[a+42>>1]=y.status);if(!K&&2===y.readyState&&0<y.responseURL.length){var S=Ri(y.responseURL);(q(),C)[a+200>>2]=S}e(a,N)}else--J};try{y.send(h)}catch(N){c(a,N)}}else c(a,"no url specified!")}var ij=(a,b)=>{(q(),C)[a>>2]=b;var c=(q(),C)[a>>2];(q(),C)[a+4>>2]=(b-c)/4294967296};
function Uc(a,b,c,d,e){function f(t){u?t():eg(t)}J+=1;var h=a+108,l=(q(),C)[h+36>>2],m=(q(),C)[h+40>>2],n=(q(),C)[h+44>>2],r=(q(),C)[h+48>>2],u=!!((q(),C)[h+52>>2]&64);hj(a,t=>{--J;f(()=>{l?M(l)(t):b?.(t)})},t=>{--J;f(()=>{m?M(m)(t):c?.(t)})},t=>{f(()=>{n?M(n)(t):d?.(t)})},t=>{f(()=>{r?M(r)(t):e?.(t)})});return a}
var Vc=()=>{throw"unwind";},jj=["default","low-power","high-performance"],Wc=(a,b)=>{var c=b>>2,d=(q(),B)[c+2];c={alpha:!!(q(),w)[b+0],depth:!!(q(),w)[b+1],stencil:!!(q(),w)[b+2],antialias:!!(q(),w)[b+3],premultipliedAlpha:!!(q(),w)[b+4],preserveDrawingBuffer:!!(q(),w)[b+5],powerPreference:jj[d],failIfMajorPerformanceCaveat:!!(q(),w)[b+12],Xi:(q(),B)[c+4],Uj:(q(),B)[c+5],fi:(q(),w)[b+24],hi:(q(),w)[b+25],$j:(q(),B)[c+7],ck:(q(),w)[b+32]};a=Ei(a);a?.canvas&&(a=a.canvas);if(!a)return 0;a.Rg&&(a=a.Rg);
if(c.hi){if(!(a.transferControlToOffscreen||"undefined"!=typeof OffscreenCanvas&&a instanceof OffscreenCanvas))return 0;if(a.transferControlToOffscreen){if(!a.kh)dg[a.id]={canvas:a.transferControlToOffscreen(),Hg:H(12),id:a.id},a.kh=!0;else if(!dg[a.id])return 0;a=dg[a.id].canvas}}if(d=a.getContext("webgl2",c)){a=H(8);(q(),C)[a+4>>2]=Ef();b={handle:a,attributes:c,version:c.Xi,Pg:d};d.canvas&&(d.canvas.vh=b);ui[a]=b;if("undefined"==typeof c.fi||c.fi)if((c=b)||(c=X),!c.Vi){c.Vi=!0;d=c.Pg;d.Vj=d.getExtension("WEBGL_multi_draw");
d.Gj=d.getExtension("EXT_polygon_offset_clamp");d.Fj=d.getExtension("EXT_clip_control");d.gk=d.getExtension("WEBGL_polygon_mode");d.wj=d.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");d.Tj=d.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=c.version&&(d.ei=d.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>c.version||!d.ei)d.ei=d.getExtension("EXT_disjoint_timer_query");for(var e of li(d))e.includes("lose_context")||e.includes("debug")||d.getExtension(e)}b.Oh=
b.Pg.getParameter(34921);b.jh=[];for(e=0;e<b.Oh;e++)b.jh[e]={enabled:!1,Ah:!1,size:0,type:0,pi:0,stride:0,Qh:0,Ci:null};b.$g=[];b.Gh=[];b.$g.length=b.Gh.length=22;b.fh=[];b.th=[];b.fh.length=b.th.length=22;b.eh=[];b.eh.length=22;for(e=0;21>=e;++e){b.eh[e]=null;b.$g[e]=b.Gh[e]=0;b.fh[e]=[];b.th[e]=[];c=b.fh[e];d=b.th[e];c.length=d.length=64;for(var f=0;64>f;++f)c[f]=d[f]=null}}else a=0;return a};
function Xc(a){X==a&&(X=0);X===ui[a]&&(X=null);"object"==typeof Y&&Y.aj(ui[a].Pg.canvas);ui[a]?.Pg.canvas&&(ui[a].Pg.canvas.vh=void 0);I(ui[a].handle);ui[a]=null}
var Yc=a=>{X=ui[a];g.ctx=U=X?.Pg;return!a||U?0:-5},kj={},mj=()=>{if(!lj){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in kj)void 0===kj[b]?delete a[b]:a[b]=kj[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);lj=c}return lj},lj;function bd(a,b){if(k)return L(31,1,a,b);var c=0,d=0,e;for(e of mj()){var f=b+c;(q(),C)[a+d>>2]=f;c+=R(e,f,Infinity)+1;d+=4}return 0}
function cd(a,b){if(k)return L(32,1,a,b);var c=mj();(q(),C)[a>>2]=c.length;a=0;for(var d of c)a+=Sg(d)+1;(q(),C)[b>>2]=a;return 0}
var gd=a=>U.activeTexture(a),hd=(a,b)=>{U.attachShader(oi[a],si[b])},jd=(a,b)=>{if(b&&!ni[b]){var c=U.createBuffer();c.name=b;ni[b]=c}34962==a?U.lh=b:34963==a&&(U.mh=b);35051==a?U.Jh=b:35052==a&&(U.Bh=b);U.bindBuffer(a,ni[b])},kd=(a,b)=>{U.bindFramebuffer(a,pi[b])},ld=(a,b)=>{U.bindRenderbuffer(a,qi[b])},md=(a,b)=>{U.bindTexture(a,ri[b])},nd=a=>{U.bindVertexArray(ti[a]);a=U.getParameter(34965);U.mh=a?a.name|0:0},od=(a,b)=>U.blendFunc(a,b),pd=(a,b,c,d)=>U.blendFuncSeparate(a,b,c,d),qd=(a,b,c,d,e,f,
h,l,m,n)=>U.blitFramebuffer(a,b,c,d,e,f,h,l,m,n),rd=(a,b,c,d)=>{c&&b?U.bufferData(a,(q(),x),d,c,b):U.bufferData(a,b,d)},sd=(a,b,c,d)=>{c&&U.bufferSubData(a,b,(q(),x),d,c)},td=a=>U.checkFramebufferStatus(a),ud=a=>U.clear(a),vd=(a,b,c,d)=>U.clearColor(a,b,c,d),wd=a=>U.clearDepth(a),xd=(a,b,c,d)=>{U.colorMask(!!a,!!b,!!c,!!d)},yd=a=>{U.compileShader(si[a])},zd=()=>{var a=yi(oi),b=U.createProgram();b.name=a;b.Eh=b.Ch=b.Dh=0;b.Vh=1;oi[a]=b;return a},Ad=a=>{var b=yi(si);si[b]=U.createShader(a);return b},
Bd=a=>U.cullFace(a),Cd=(a,b)=>{for(var c=0;c<a;c++){var d=(q(),B)[b+4*c>>2],e=ni[d];e&&(U.deleteBuffer(e),e.name=0,ni[d]=null,d==U.lh&&(U.lh=0),d==U.mh&&(U.mh=0),d==U.Jh&&(U.Jh=0),d==U.Bh&&(U.Bh=0))}},Dd=(a,b)=>{for(var c=0;c<a;++c){var d=(q(),B)[b+4*c>>2],e=pi[d];e&&(U.deleteFramebuffer(e),e.name=0,pi[d]=null)}},Ed=a=>{if(a){var b=oi[a];b?(U.deleteProgram(b),b.name=0,oi[a]=null):V||=1281}},Fd=(a,b)=>{for(var c=0;c<a;c++){var d=(q(),B)[b+4*c>>2],e=qi[d];e&&(U.deleteRenderbuffer(e),e.name=0,qi[d]=
null)}},Gd=a=>{if(a){var b=si[a];b?(U.deleteShader(b),si[a]=null):V||=1281}},Hd=(a,b)=>{for(var c=0;c<a;c++){var d=(q(),B)[b+4*c>>2],e=ri[d];e&&(U.deleteTexture(e),e.name=0,ri[d]=null)}},Id=(a,b)=>{for(var c=0;c<a;c++){var d=(q(),B)[b+4*c>>2];U.deleteVertexArray(ti[d]);ti[d]=null}},Jd=a=>U.depthFunc(a),Kd=a=>{U.depthMask(!!a)},Ld=(a,b)=>{U.detachShader(oi[a],si[b])},Md=a=>U.disable(a),Nd=(a,b,c)=>{Ci(b+c);U.drawArrays(a,b,c);Bi&&U.bindBuffer(34962,ni[U.lh])},nj=[],Od=(a,b)=>{for(var c=nj[a],d=0;d<
a;d++)c[d]=(q(),B)[b+4*d>>2];U.drawBuffers(c)},Pd=(a,b,c,d)=>{var e=0;if(!U.mh){var f=1*vi[c-5120]*b;var h=Ai(f);U.bindBuffer(34963,h);U.bufferSubData(34963,0,(q(),x).subarray(d,d+f));if(0<b)for(h=0;h<X.Oh;++h)if(f=X.jh[h],f.Ah&&f.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:V||=1282;return}e=(new e((q(),x).buffer,d,b)).reduce((l,m)=>Math.max(l,m))+1;break}d=0}Ci(e);U.drawElements(a,b,c,d);Bi&&U.bindBuffer(34962,ni[U.lh]);U.mh||
U.bindBuffer(34963,null)},Qd=a=>U.enable(a),Rd=a=>{X.jh[a].enabled=!0;U.enableVertexAttribArray(a)},Sd=(a,b,c,d)=>{U.framebufferRenderbuffer(a,b,c,qi[d])},Td=(a,b,c,d,e)=>{U.framebufferTexture2D(a,b,c,ri[d],e)},Ud=a=>U.frontFace(a),Vd=(a,b)=>{zi(a,b,"createBuffer",ni)},Wd=(a,b)=>{zi(a,b,"createFramebuffer",pi)},Xd=(a,b)=>{zi(a,b,"createRenderbuffer",qi)},Yd=(a,b)=>{zi(a,b,"createTexture",ri)},Zd=(a,b)=>{zi(a,b,"createVertexArray",ti)},$d=a=>U.generateMipmap(a),ae=(a,b,c,d)=>{a=U.getAttachedShaders(oi[a]);
var e=a.length;e>b&&(e=b);(q(),B)[c>>2]=e;for(b=0;b<e;++b)c=si.indexOf(a[b]),(q(),B)[d+4*b>>2]=c},be=(a,b)=>U.getAttribLocation(oi[a],P(b)),oj=()=>{var a=li(U);return a=a.concat(a.map(b=>"GL_"+b))},pj=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(V||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=U.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>X.version){V||=1282;return}d=oj().length;break;case 33307:case 33308:if(2>X.version){V||=1280;
return}d=33307==a?3:0}if(void 0===d)switch(e=U.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:V||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof
Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:(q(),B)[b+4*a>>2]=e[a];break;case 2:(q(),Ea)[b+4*a>>2]=e[a];break;case 4:(q(),w)[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){V||=1280;p(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:V||=1280;p(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:ij(b,d);break;case 0:(q(),
B)[b>>2]=d;break;case 2:(q(),Ea)[b>>2]=d;break;case 4:(q(),w)[b]=d?1:0}}else V||=1281},ce=(a,b)=>pj(a,b,4),de=()=>{var a=U.getError()||V;V=0;return a},ee=(a,b)=>pj(a,b,0),fe=(a,b,c,d)=>{a=U.getProgramInfoLog(oi[a]);null===a&&(a="(unknown error)");b=0<b&&d?R(a,d,b):0;c&&((q(),B)[c>>2]=b)},ie=(a,b,c)=>{if(c)if(a>=mi)V||=1281;else if(a=oi[a],35716==b)a=U.getProgramInfoLog(a),null===a&&(a="(unknown error)"),(q(),B)[c>>2]=a.length+1;else if(35719==b){if(!a.Eh){var d=U.getProgramParameter(a,35718);for(b=
0;b<d;++b)a.Eh=Math.max(a.Eh,U.getActiveUniform(a,b).name.length+1)}(q(),B)[c>>2]=a.Eh}else if(35722==b){if(!a.Ch)for(d=U.getProgramParameter(a,35721),b=0;b<d;++b)a.Ch=Math.max(a.Ch,U.getActiveAttrib(a,b).name.length+1);(q(),B)[c>>2]=a.Ch}else if(35381==b){if(!a.Dh)for(d=U.getProgramParameter(a,35382),b=0;b<d;++b)a.Dh=Math.max(a.Dh,U.getActiveUniformBlockName(a,b).length+1);(q(),B)[c>>2]=a.Dh}else(q(),B)[c>>2]=U.getProgramParameter(a,b);else V||=1281},je=(a,b,c,d)=>{a=U.getShaderInfoLog(si[a]);null===
a&&(a="(unknown error)");b=0<b&&d?R(a,d,b):0;c&&((q(),B)[c>>2]=b)},ke=(a,b,c)=>{c?35716==b?(a=U.getShaderInfoLog(si[a]),null===a&&(a="(unknown error)"),a=a?a.length+1:0,(q(),B)[c>>2]=a):35720==b?(a=(a=U.getShaderSource(si[a]))?a.length+1:0,(q(),B)[c>>2]=a):(q(),B)[c>>2]=U.getShaderParameter(si[a],b):V||=1281},qj=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),le=(a,b)=>{b=P(b);if(a=oi[a]){var c=a,d=c.uh,e=c.Bi,f;if(!d){c.uh=d={};c.Ai={};var h=U.getProgramParameter(c,35718);for(f=0;f<h;++f){var l=U.getActiveUniform(c,
f);var m=l.name;l=l.size;var n=qj(m);n=0<n?m.slice(0,n):m;var r=c.Vh;c.Vh+=l;e[n]=[l,r];for(m=0;m<l;++m)d[r]=m,c.Ai[r++]=n}}c=a.uh;d=0;e=b;f=qj(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Bi[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else V||=1281;return-1},me=a=>(a=ni[a])?U.isBuffer(a):0,ne=a=>U.isEnabled(a),oe=a=>(a=pi[a])?U.isFramebuffer(a):0,pe=a=>(a=oi[a])?U.isProgram(a):0,qe=a=>(a=qi[a])?U.isRenderbuffer(a):0,re=a=>(a=si[a])?U.isShader(a):0,se=a=>
(a=ri[a])?U.isTexture(a):0,te=a=>{a=oi[a];U.linkProgram(a);a.uh=0;a.Bi={}},ue=(a,b)=>{3317==a?wi=b:3314==a&&(xi=b);U.pixelStorei(a,b)},ve=(a,b)=>U.polygonOffset(a,b),we=a=>U.readBuffer(a),rj=a=>{a-=5120;return 0==a?(q(),w):1==a?(q(),x):2==a?(q(),A):4==a?(q(),B):6==a?(q(),Ea):5==a||28922==a||28520==a||30779==a||30782==a?(q(),C):(q(),Da)},xe=(a,b,c,d,e,f,h)=>{if(U.Jh)U.readPixels(a,b,c,d,e,f,h);else{var l=rj(f);h>>>=31-Math.clz32(l.BYTES_PER_ELEMENT);U.readPixels(a,b,c,d,e,f,l,h)}},ye=(a,b,c,d)=>U.renderbufferStorage(a,
b,c,d),ze=(a,b,c,d,e)=>U.renderbufferStorageMultisample(a,b,c,d,e),Ae=(a,b,c,d)=>U.scissor(a,b,c,d),Be=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var h=d?(q(),C)[d+4*f>>2]:void 0;e+=P((q(),C)[c+4*f>>2],h)}U.shaderSource(si[a],e)},sj=(a,b,c,d,e)=>{a=rj(a);b=d*((xi||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+wi-1&-wi);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Ce=(a,b,c,d,e,f,h,l,m)=>{if(U.Bh)U.texImage2D(a,
b,c,d,e,f,h,l,m);else if(m){var n=rj(l);m>>>=31-Math.clz32(n.BYTES_PER_ELEMENT);U.texImage2D(a,b,c,d,e,f,h,l,n,m)}else n=m?sj(l,h,d,e,m):null,U.texImage2D(a,b,c,d,e,f,h,l,n)},De=(a,b,c)=>U.texParameteri(a,b,c),Ee=(a,b,c,d,e,f,h,l,m)=>{if(U.Bh)U.texSubImage2D(a,b,c,d,e,f,h,l,m);else if(m){var n=rj(l);U.texSubImage2D(a,b,c,d,e,f,h,l,n,m>>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else m=m?sj(l,h,e,f,m):null,U.texSubImage2D(a,b,c,d,e,f,h,l,m)},tj=a=>{var b=U.Li;if(b){var c=b.uh[a];"number"==typeof c&&(b.uh[a]=
c=U.getUniformLocation(b,b.Ai[a]+(0<c?`[${c}]`:"")));return c}V||=1282},Fe=(a,b)=>{U.uniform1f(tj(a),b)},Ge=(a,b)=>{U.uniform1i(tj(a),b)},He=(a,b,c)=>{b&&U.uniform2fv(tj(a),(q(),Ea),c>>2,2*b)},Ie=(a,b,c)=>{b&&U.uniform3fv(tj(a),(q(),Ea),c>>2,3*b)},Je=(a,b,c,d,e)=>{U.uniform4f(tj(a),b,c,d,e)},Ke=(a,b,c)=>{b&&U.uniform4fv(tj(a),(q(),Ea),c>>2,4*b)},Le=(a,b,c,d)=>{b&&U.uniformMatrix4fv(tj(a),!!c,(q(),Ea),d>>2,16*b)},Me=a=>{a=oi[a];U.useProgram(a);U.Li=a},Ne=(a,b,c,d,e,f)=>{var h=X.jh[a];U.lh?(h.Ah=!1,
U.vertexAttribPointer(a,b,c,!!d,e,f)):(h.size=b,h.type=c,h.pi=d,h.stride=e,h.Qh=f,h.Ah=!0,h.Ci=function(l,m,n,r,u,t){this.vertexAttribPointer(l,m,n,r,u,t)})},Oe=(a,b,c,d)=>U.viewport(a,b,c,d),Z={},uj=2;function vj(a){if(a){for(;Z[uj];)uj=2147483647>uj?uj+1:2;Z[uj]=a;a.Ei=uj;return uj++}}function Se(a){navigator.gpu.requestAdapter().then(b=>{M(a)(vj(b))})}var wj=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),xj=a=>{(xj=wj())(a)},Ve=(a,b)=>{xj((q(),x).subarray(a,a+b));return 0};
function yj(a,b){if(a){var c=vj(a);a.si=b;b.nh||(b.nh=new Map);b.nh.set(c,a);return c}}function $e(a,b){Z[a].requestDevice().then(c=>{yj(c.queue,c);M(b)(yj(c,Z[a]))})}function af(a,b,c){a=Z[a];try{a.Nh[b]=a.getMappedRange(b,0>c?void 0:c)}catch(d){return-1}return b}function bf(a,b,c,d,e,f){Z[a].mapAsync(d,e,0>f?void 0:f).then(()=>{M(b)(a,c,d,e,f)})}function cf(a,b,c,d,e){(q(),x).set(new Uint8Array(Z[a].Nh[b],c,e),d)}function df(a){a=Z[a];a.unmap();a.Nh={}}
function ef(a,b){a=Z[a];b>>=2;var c;if(b){var d=(q(),C)[b];d?(d={querySet:Z[d]},0<=(c=(q(),B)[b+1])&&(d.beginningOfPassWriteIndex=c),0<=(c=(q(),B)[b+2])&&(d.endOfPassWriteIndex=c),c=d):c=void 0;c={timestampWrites:c}}else c=void 0;return vj(a.beginComputePass(c))}function ff(a,b,c,d,e,f){Z[a].copyBufferToBuffer(Z[b],c,Z[d],e,f)}function gf(a,b,c,d){Z[a].dispatchWorkgroups(b,c,d)}function zj(a){return Number((q(),Ga)[a>>>1])}
function hf(a,b,c,d){a=Z[a];c>>=2;let e=[];for(;d--;){let f=Z[(q(),C)[c+1]];e.push({binding:(q(),C)[c],resource:f.isBuffer?{buffer:f,offset:zj(c+2),size:zj(c+4)||void 0}:f});c+=6}return yj(a.createBindGroup({layout:Z[b],entries:e}),a)}function jf(a,b){a=Z[a];b>>=2;b={size:zj(b),usage:(q(),C)[b+2],mappedAtCreation:!!(q(),C)[b+3]};b=a.createBuffer(b);b.Nh={};b.isBuffer=1;return yj(b,a)}function kf(a){return yj(Z[a].createCommandEncoder(void 0),Z[a])}var Aj="auto";
function lf(a,b,c,d,e,f){a=Z[a];d=1<d?Z[d]:Aj;b=Z[b];c=P(c)||void 0;let h={};for(;f--;)h[P((q(),C)[e+3>>2])]=(q(),F)[e+8>>3],e+=16;return yj(a.createComputePipeline({layout:d,compute:{module:b,entryPoint:c,constants:h}}),a)}function mf(a,b){var c=b>>2;b=P((q(),C)[c]);var d=c+2;c=(q(),B)[d+2];let e=[];d=(q(),C)[d]>>2;let f;for(;c--;)f=(q(),C)[d+2],e.push({entryPoint:P((q(),C)[d]),layout:1<f?Z[f]:f?Aj:null}),d+=4;return yj(Z[a].createShaderModule({code:b,compilationHints:e}),Z[a])}
function nf(a){return Z[a].queue.Ei}function of(a,b,c){Z[a].lost.then(d=>{var e="destroyed"==d.reason?1:0;if(d=d.message){var f=Pf(),h=Sg(d)+1,l=Of(h);R(d,l,h)}M(b)(a,e,l,c);f&&Nf(f)})}function Bj(a){let b=Z[a];b&&(b.Ei=0,b.destroy&&b.destroy(),b.nh&&b.nh.forEach((c,d)=>{Bj(d)}),b.si&&b.si.nh.delete(a),delete Z[a])}function pf(a){Z[a].end();Bj(a)}function qf(a){let b=Z[a].finish();Bj(a);return vj(b)}function rf(a,b,c,d,e){0===e?Z[a].setBindGroup(b,Z[c]):Z[a].setBindGroup(b,Z[c],(q(),C),d>>2,e)}
function sf(a,b){Z[a].setPipeline(Z[b])}function tf(a,b){return vj(Z[a].getBindGroupLayout(b))}function uf(a,b,c){Z[a].onSubmittedWorkDone().then(()=>{M(b)(a,c)})}function vf(a,b){Z[a].submit([Z[b]]);Bj(b)}function wf(a,b,c,d,e){Z[a].writeBuffer(Z[b],c,(q(),x),d,e)}
var xf=(a,b)=>{function c(d){a(d,b)&&requestAnimationFrame(c)}a=M(a);requestAnimationFrame(c)},Cj=(a,b,c,d)=>{var e={string:n=>{var r=0;if(null!==n&&void 0!==n&&0!==n){r=Sg(n)+1;var u=Of(r);R(n,u,r);r=u}return r},array:n=>{var r=Of(n.length);(q(),w).set(n,r);return r}};a=g["_"+a];var f=[],h=0;if(d)for(var l=0;l<d.length;l++){var m=e[c[l]];m?(0===h&&(h=Pf()),f[l]=m(d[l])):f[l]=d[l]}c=a(...f);return c=function(n){0!==h&&Nf(h);return"string"===b?P(n):"boolean"===b?!!n:n}(c)};
g.requestAnimationFrame=zh;g.pauseMainLoop=Kh;g.resumeMainLoop=function(){Ch++;var a=sh,b=th,c=uh;uh=null;Jh(c,0,!1,Dh,!0);Bh(a,b);wh()};var Dj=()=>{if(X){var a=X.fh;X.fh=X.th;X.th=a;a=X.$g;X.$g=X.Gh;X.Gh=a;for(a=0;21>=a;++a)X.$g[a]=0}};"undefined"!=typeof Mh&&Hh.push(Dj);(async function(){ki=new gj})();var Ej=()=>{X&&!cg.tj&&!X.attributes.hi&&X.Pg.commit&&X.Pg.commit()};"undefined"!=typeof Mh&&Hh.push(Ej);for(let a=0;32>a;++a)nj.push(Array(a));
if(!k){var Fj=/iPad|iPhone|iPod/.test("undefined"!==typeof navigator?navigator.userAgent:"");la=new WebAssembly.Memory({initial:(Fj?536870912:134217728)/65536,maximum:(Fj?536870912:2147483648)/65536,shared:!0});ma()}g.print&&(ha=g.print);g.ccall=Cj;g.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?g["_"+a]:(...f)=>Cj(a,b,c,f,d)};
var eh=[Ue,$f,kg,Hb,Tb,Ub,Vb,Zb,Wb,Xb,Yb,$b,ac,bc,cc,dc,qc,Gi,sc,tc,Vi,Gc,Hc,Ic,Lc,Mc,Nc,Oc,Pc,Qc,Rc,bd,cd],dh={3836184:(a,b,c,d,e)=>{if("undefined"==typeof g||!g.Hi)return 1;a=P(Number(a>>>0));a.startsWith("./")&&(a=a.substring(2));a=g.Hi.get(a);if(!a)return 2;b=Number(b>>>0);c=Number(c>>>0);d=Number(d>>>0);if(b+c>a.byteLength)return 3;try{const f=a.subarray(b,b+c);switch(e){case 0:(q(),x).set(f,d);break;case 1:g.lj?g.lj(d,f):g.Sj(d,f);break;default:return 4}return 0}catch{return 4}},3837008:()=>
{if("undefined"!==typeof window){if(window.close)try{window.close()}catch(a){}window.parent&&window.parent!==window&&window.parent.postMessage&&window.parent.postMessage({type:"shenai-exit-app"},"*")}},3837252:()=>g.MxCaptureRunning?1:0,3837299:a=>{a=P(a).slice(1);document.getElementById(a)?.addEventListener("pointerup",()=>{if("function"===typeof DeviceMotionEvent?.requestPermission)try{DeviceMotionEvent.requestPermission().then(b=>{"granted"===b&&console.warn("DeviceMotion permission not granted")}).catch(b=>
{console.error("DeviceMotion request failed:",b)})}catch(b){console.error("DeviceMotionEvent.requestPermission() failed:",b)}},{once:!0})},3837902:a=>{a=P(a).replace(/^#/,"");const b=document.getElementById(a),c=document.createElement("canvas");c.width=b.width;c.height=b.height;c.style=b.style;b.replaceWith(c);c.id=a},3838215:()=>/Mobile|Android|iPhone|iPad/i.test(navigator.userAgent),3838283:()=>{let a=!0;const b=()=>{let f=null,h=0;return{ptr:()=>f,ensure:l=>{(null===f||l>h)&&0<l&&(null!==f&&I(f),
f=H(l),h=l)},clean:()=>{null!==f&&(I(f),f=null,h=0)}}},c=b(),d=b(),e=self.onmessage;self.onmessage=f=>{if("MxStartFrameProcessing"===f.data.cmd)a=!0;else if("MxFinishFrameProcessing"===f.data.cmd)a=!1,c.clean(),d.clean();else if("MxProcessFrame"===f.data.cmd){if(a){var h=f.data.frame,l=f.data.format,m=f.data.width,n=f.data.height,r=f.data.timestamp,u=f.data.change_id,t=f.data.facing_user,v=f.data.full_frame_processing,z=f.data.device_id,O=f.data.custom_aspect_ratio;f=f.data.exposure_json;if("string"===
typeof f&&0<f.length){var D=Sg(f)+1;d.ensure(D);R(f,d.ptr(),D)}if(h instanceof ImageData){f=h.data;c.ensure(f.byteLength);D=c.ptr();(q(),x).set(f,D);const G=d.ptr();g._ingestCameraFrame(D,f.byteLength,l,m,n,r,u,t,v,z,O,G)}else{f={rect:{x:0,y:0,width:m,height:n}};D=h.allocationSize(f);c.ensure(D);const G=c.ptr(),E=(q(),x).subarray(G,G+D),K=d.ptr();h.copyTo(E,f).then(()=>{h.close();g._ingestCameraFrame(G,E.byteLength,l,m,n,r,u,t,v,z,O,K)})}}}else e(f)}},3840990:a=>{const b=a.toString();g.MxStartFrameProcessing=
()=>{Xf[b].postMessage({cmd:"MxStartFrameProcessing"})};g.MxFinishFrameProcessing=()=>{Xf[b].postMessage({cmd:"MxFinishFrameProcessing"})};g.MxDispatchFrameToThread=(c,d,e,f,h,l,m,n,r,u)=>{const t=Xf[b];var v=g.MxCameraHelpers;v=v&&v.di?v.di():null;t.postMessage({cmd:"MxProcessFrame",frame:c,format:d,width:e,height:f,timestamp:h,change_id:l,facing_user:m,full_frame_processing:n,device_id:r,custom_aspect_ratio:u,exposure_json:v},[c instanceof ImageData?c.data.buffer:c])}},3842078:()=>{g.MxStartFrameProcessing&&
g.MxStartFrameProcessing()},3842160:()=>{g.MxFinishFrameProcessing&&g.MxFinishFrameProcessing()},3842244:()=>{window.MxClosePreloadDisplay?.()},3842285:a=>{a=P(a);window.MxUpdatePreloadDisplay?.(a)},3842362:a=>{const b=P(a),c=performance.now(),d=()=>window.MxUpdatePreloadDisplay?.(b,c);navigator.permissions.query({name:"camera"}).then(e=>{"prompt"==e.state&&d()}).catch(()=>{setTimeout(d,1E3)})},3842795:a=>{console.log(P(a))},3842830:a=>{console.log(P(a))},3842865:(a,b)=>{fetch("https://telemetry.shen.ai/v1/traces",
{method:"POST",body:P(a),headers:{"Content-Type":"application/json","X-Shen-Telemetry-Transport":"http"},keepalive:b})},3843060:()=>"undefined"!==typeof wasmOffsetConverter};function Sb(){window.Mg||(window.Mg=function(){g._handlePagehide()},window.addEventListener("pagehide",window.Mg))}function Xe(){window.Mg&&(window.removeEventListener("pagehide",window.Mg),delete window.Mg)}
function Zc(){navigator.storage&&navigator.storage.persist&&navigator.storage.persist().then(function(a){a||console.log("[Shen.AI SDK] Could not obtain persistent storage (storage may be cleared under pressure).")}).catch(function(a){console.log("[Shen.AI SDK] Error requesting persistent storage:",a)})}
function ad(){(void 0===g.MxCaptureRunning?navigator.mediaDevices.getUserMedia({video:!0}):Promise.resolve()).then(()=>{navigator.mediaDevices.enumerateDevices().then(a=>{g.MxVideoDevices=a.filter(b=>"videoinput"==b.kind).map(b=>({id:b.deviceId??"",label:b.label??""}));g._onVideoDevicesEnumerated()}).catch(()=>{g._onVideoDevicesEnumerationError()})}).catch(()=>{g._onVideoDevicesEnumerationError()})}function fd(){const a=JSON.stringify(g.MxVideoDevices),b=Sg(a)+1,c=H(b);R(a,c,b);return c}
function $c(){g.MxCameraHelpers||(g.MxCameraHelpers=(()=>{function a(e){void 0==g.MxCaptureRunning?(g.MxCaptureRunning=!1,e()):setTimeout(a,100,e)}const b=480/720,c={unsupported:0,I420:1,I420A:2,RGBA:3,RGBX:4,BGRA:5,BGRX:6,NV12:7},d=(e,f,h,l=0)=>{let m=e,n=f,r={x:0,y:0};if(!h){let u=h=m/n;if(0<l)u=l;else if(.6>h||.75<h)u=b;h<u?(n=Math.round(m/u),n-=n&1,r.y=Math.floor((f-n)/2)):h>u&&(m=Math.round(n*u),m-=m&1,r.x=Math.floor((e-m)/2))}return{width:m,height:n,offset:r}};return{Gi:30,Zh:b,Fi:.75,mj:c,
Oj:d,di:()=>{try{var e=g.MxVideoTrack;if(!e||!e.getSettings)return null;const f=e.getSettings(),h=e.getCapabilities?e.getCapabilities():void 0;e=E=>"number"===typeof E?Math.round(1E9*E):null;const l=E=>"number"===typeof E&&0<E?Math.round(1E9/E):null,m=h&&h.exposureCompensation?h.exposureCompensation:void 0,n=h&&h.Kh?h.Kh:void 0,r=h&&h.frameRate?h.frameRate:void 0,u=h&&h.iso?h.iso:void 0,t=l(f.frameRate),v=r?l(r.max):null,z=r?l(r.min):null,O=void 0!==f.Kh?e(f.Kh):null,D=n?e(n.min):null,G=n?e(n.max):
null;return JSON.stringify({iso:void 0!==f.iso?f.iso:null,Rj:u&&void 0!==u.min?u.min:null,Qj:u&&void 0!==u.max?u.max:null,Ej:O,Dj:D,Cj:G,Kj:t,Jj:v,Ij:z,xj:void 0!==f.exposureCompensation?f.exposureCompensation:null,zj:m&&void 0!==m.min?m.min:null,yj:m&&void 0!==m.max?m.max:null,Aj:m&&void 0!==m.step?m.step:null,Bj:f.exposureMode||null,ai:void 0!==f.ai?f.ai:null,nj:f.exposureMode?"manual"===f.exposureMode:null,pj:f.whiteBalanceMode?"manual"===f.whiteBalanceMode:null})}catch(f){return console.error("Failed to gather camera parameters",
f),null}},yi:(e,f,h,l,m,n,r)=>{g.MxCaptureRunning=!0;g._onCameraInitialized();const u=e.readable.getReader(),t=async()=>{if(g.MxCaptureRunning)try{const z=await u.read();if(z.value){var v=z.value;g.MxDispatchFrameToThread?g.MxDispatchFrameToThread(v,c[v.format]??c.unsupported,v.codedWidth,v.codedHeight,BigInt(v.timestamp),h,l,m,n,r):v.close();t()}else setTimeout(t,1E3/30)}catch(z){console.error("Error reading frame:",z)}else try{u.releaseLock(),f.stop(),g.MxCaptureRunning=void 0,g.MxVideoTrack=void 0}catch(z){console.error("Error stopping video:",
z)}};t()},xi:(e,f,h,l,m,n,r)=>{const u=new OffscreenCanvas(1,1);let t=u.getContext("2d",{willReadFrequently:!0});const v=document.createElement("video");v.setAttribute("id","shen-camera-proxy");v.setAttribute("playsinline","");v.setAttribute("muted","");v.setAttribute("disablepictureinpicture","");v.style.position="absolute";v.style.top="0";v.style.left="0";v.style.width="1px";v.style.height="1px";document.body.appendChild(v);let z=null,O=0;const D=()=>{clearTimeout(O);try{v.onplay=null,v.onloadedmetadata=
null,v.pause(),v.srcObject=null,v.removeAttribute("src"),v.load(),v.remove(),f.stop()}catch(G){console.error("Error cleaning up video:",G)}u.width=0;u.height=0;z=t=null;g.MxCaptureRunning=void 0;g.MxVideoTrack=void 0};v.onloadedmetadata=()=>{z=d(v.videoWidth,v.videoHeight,m,r);u.width=z.width;u.height=z.height;v.play()};v.onplay=()=>{g.MxCaptureRunning=!0;g._onCameraInitialized();const G=1E3/30,E=()=>{if(g.MxCaptureRunning)try{const K=performance.now();if(z){t.drawImage(v,z.offset.x,z.offset.y,z.width,
z.height,0,0,z.width,z.height);const y=t.getImageData(0,0,z.width,z.height),W=Math.round(1E3*K);g.MxDispatchFrameToThread&&g.MxDispatchFrameToThread(y,c.RGBA,z.width,z.height,BigInt(W),h,l,m,n,r)}O=setTimeout(E,Math.max(0,G-(performance.now()-K)))}catch(K){console.error("Error capturing frame:",K),D()}else D()};E()};v.srcObject=e},Di:a}})())}
function Pe(a,b,c,d,e){const f=g.MxCameraHelpers,h=P(e),l=(()=>{if(""===h)return-1;void 0===g.MxDeviceIdStrToIntMap&&(g.MxDeviceIdStrToIntMap=new Map);let n=g.MxDeviceIdStrToIntMap.get(h);void 0===n&&(n=g.MxDeviceIdStrToIntMap.size,g.MxDeviceIdStrToIntMap.set(h,n));return n})(),m={video:(()=>{var n=/Mobile|Android|iPhone|iPad/i.test(navigator.userAgent),r=/MacIntel|Macintosh/i.test(navigator.userAgent);const u={ideal:/iPhone|iPad/i.test(navigator.userAgent)?480:r?640:720,min:480};r=0<d?{ideal:n?1/
d:d}:{ideal:n?1/f.Zh:r?f.Fi:f.Zh};n={frameRate:{ideal:f.Gi},aspectRatio:c?void 0:r,width:n?u:void 0,height:n?void 0:u,resizeMode:n?void 0:{exact:"none"}};""!==h?n.deviceId={exact:h}:n.facingMode={ideal:b?"user":"environment"};return n})()};f.Di(function(){navigator.mediaDevices.getUserMedia(m).then(n=>{const r=n.getVideoTracks()[0];"undefined"!==typeof MediaStreamTrackProcessor?f.yi(new MediaStreamTrackProcessor({track:r}),r,a,b,c,l,d):f.xi(n,r,a,b,c,l,d);g.MxVideoTrack=r}).catch(n=>{g.MxCaptureRunning=
void 0;g.MxVideoTrack=void 0;g._onCameraInitializationError();console.error("Camera initialization error:",n)})})}
function Qe(a,b,c,d,e){const f=g.MxCameraHelpers,h=Ag(a);f.Di(function(){try{const l=h.getVideoTracks()[0];"undefined"!==typeof MediaStreamTrackProcessor?f.yi(new MediaStreamTrackProcessor({track:l}),l,b,c,d,-1,e):f.xi(h,l,b,c,d,-1,e);g.MxVideoTrack=l}catch(l){g.MxCaptureRunning=void 0,g.MxVideoTrack=void 0,g._onCameraInitializationError(),console.error("Media stream initialization error:",l)}})}function fc(){g.MxCaptureRunning&&(g.MxCaptureRunning=!1)}
function Ze(a){const b=g.MxVideoTrack;if(b&&"undefined"!==typeof b.getCapabilities){const c=b.getCapabilities();b.getSettings();const d={advanced:[]};c.whiteBalanceMode&&d.advanced.push({whiteBalanceMode:a?"manual":"continuous"});0<d.advanced.length&&b.applyConstraints(d).catch(()=>{})}}function Ye(){"wakeLock"in navigator&&navigator.wakeLock.request("screen").then(a=>g.MxWakeLock=a).catch(()=>{})}function We(){g.MxWakeLock&&g.MxWakeLock.release().then(()=>g.MxWakeLock=null).catch(()=>{})}
function gc(){navigator.bluetooth?(console.log("[PolarH10] Starting doScan... requesting device with name 'Polar H10'"),g.polar||(g.polar={device:null,server:null,pmdService:null,controlChar:null,dataChar:null}),navigator.bluetooth.requestDevice({filters:[{namePrefix:"Polar H10"}],optionalServices:["fb005c80-02e7-f387-1cad-8acd2d8df0c8"]}).then(a=>{console.log("[PolarH10] Device chosen:",a);g.polar.device=a;return a.gatt.connect()}).then(a=>{console.log("[PolarH10] GATT connected");g.polar.server=
a;return a.getPrimaryService("fb005c80-02e7-f387-1cad-8acd2d8df0c8")}).then(a=>{console.log("[PolarH10] Found PMD service");g.polar.pmdService=a;return Promise.all([a.getCharacteristic("fb005c81-02e7-f387-1cad-8acd2d8df0c8"),a.getCharacteristic("fb005c82-02e7-f387-1cad-8acd2d8df0c8")])}).then(a=>{const b=a[0];a=a[1];console.log("[PolarH10] Found control & data characteristics");g.polar.controlChar=b;g.polar.dataChar=a;return Promise.all([b.startNotifications(),a.startNotifications()])}).then(()=>
{console.log("[PolarH10] Notifications started");const a=g.polar.dataChar;g.polar.controlChar.addEventListener("characteristicvaluechanged",b=>{b=new Uint8Array(b.target.value.buffer);const c=H(b.length);(q(),x).set(b,c);g._onBleControlNotification(c,b.length);I(c)});a.addEventListener("characteristicvaluechanged",b=>{b=new Uint8Array(b.target.value.buffer);const c=H(b.length);(q(),x).set(b,c);g._onBleDataNotification(c,b.length);I(c)});g._onBleDeviceReady()}).catch(a=>{console.error("[PolarH10] doScan() error:",
a)})):console.error("Web Bluetooth not supported by this browser")}function yf(a,b){if(g.polar&&g.polar.controlChar){var c=new Uint8Array(b);for(let d=0;d<b;d++)c[d]=(q(),x)[a+d];g.polar.controlChar.writeValue(c).then(()=>{console.log("[PolarH10] ControlChar write success")}).catch(d=>{console.error("[PolarH10] ControlChar write error:",d)})}else console.warn("[PolarH10] No polar.controlChar to write to")}
function Re(a,b){const c=P(a),d=P(b);navigator.bluetooth?(g.bm||(g.bm={Mi:null,cj:null,vi:null}),navigator.bluetooth.requestDevice({filters:[{namePrefix:"BM"},{namePrefix:"Berry"},{services:[c]}],optionalServices:[c]}).then(e=>(g.bm.Mi=e,e.gatt.connect())).then(e=>(g.bm.cj=e,e.getPrimaryService(c))).then(e=>e.getCharacteristic(d)).then(e=>{g.bm.vi=e;return e.startNotifications()}).then(()=>{console.log("[BM1000C] notifications ON");g._bm_onReady();g.bm.vi.addEventListener("characteristicvaluechanged",
e=>{e=new Uint8Array(e.target.value.buffer);const f=H(e.length);(q(),x).set(e,f);g._bm_onRx(f,e.length);I(f)})}).catch(e=>console.error("[BM1000C] scan/connect error:",e))):console.error("Web Bluetooth not supported")}function Te(a){a=P(a);"undefined"!==typeof window&&window.open(a,"_blank")}
function ed(){var a=navigator.userAgent,b="unknown",c="unknown",d=!0,e=navigator.language;-1!==a.indexOf("Chrome")?(b="Chrome",c=a.substr(a.indexOf("Chrome")+7,12)):-1!==a.indexOf("Safari")?(b="Safari",c=a.substr(a.indexOf("Version")+8,8)):-1!==a.indexOf("Firefox")?(b="Firefox",c=a.substr(a.indexOf("Firefox")+8,12)):-1!==a.indexOf("Opera")||-1!==a.indexOf("OPR")?(b="Opera",c=a.substr(a.indexOf("Version")+8,12)):-1!==a.indexOf("Edge")&&(b="Edge",c=a.substr(a.indexOf("Edge")+5,12));if(-1!==a.indexOf("Android"))a=
"Android";else{if("iPad"===navigator.platform||/\b(iPad)\b/i.test(navigator.userAgent||""))var f=!0;else{f="MacIntel"===navigator.platform&&2<navigator.maxTouchPoints;var h="undefined"!==typeof window&&"function"===typeof window.matchMedia?window.matchMedia("(hover: none) and (pointer: coarse)").matches:!1;f=f&&h}f||-1!==a.indexOf("iPhone")||-1!==a.indexOf("iPad")||-1!==a.indexOf("iPod")?a="iOS":-1!==a.indexOf("Mobile")?a="Unknown (mobile)":(a=-1!==a.indexOf("Mac OS")?"Mac OS":-1!==a.indexOf("Windows")?
"Windows":-1!==a.indexOf("Linux")?"Linux":"Unknown (desktop)",d=!1)}b=JSON.stringify({browser:b,version:c,os:a,is_mobile:d,language:e});c=Sg(b)+1;d=H(c);R(b,d,c);return d}function Ta(){return"undefined"!==typeof wasmOffsetConverter}var Af,za,Bf,Cf,Df,H,Ef,I,Ff,Gf,va,Ca,Hf,If,Jf,Kf,Lf,Ma,Mf,Nf,Of,Pf,Qf,Sa;function ta(){if(k)na?.(g),Ja();else{for(var a=Tf;0<a.length;)a.shift()(g);g.calledRun=!0;if(!ja){Ja();na?.(g);g.onRuntimeInitialized?.();a=Df;try{var b=a(0,0);dd(b,!0)}catch(c){$g(c)}}}}var Ka;
k||(Ka=await (sa()),ta());Ha?moduleRtn=g:moduleRtn=new Promise((a,b)=>{na=a;oa=b});
;return moduleRtn}export default Module;var isPthread=globalThis.self?.name?.startsWith("em-pthread");isPthread&&Module();
